### ISSUE TITLE
Hierarchical_Collapse collapses on IPython-specific shortcuts

### ISSUE THREAD

**Issue by tylerhartley** [ipython-contrib/IPython-notebook-extensions#106]
The "x" cut-cell hotkey in IPython also triggers the collapse of a group of cells with the hierarchical_collapse extension running. Details:

On Windows machine, running Python 2.7.3, IPython 2.2, running notebooks extensions from the 2.x branch. Hierarchical_collapse is the only enabled extension.

**Comment by jat255** [comment]
This occurs for me too using Python 2.7.9, IPython 2.3.1, extensions from 2.x branch.

**Comment by juhasch** [comment]
Extension now replaced by collapsible_headings
