### ISSUE TITLE
Potential issue on returning Python string containing URL

### ISSUE THREAD

**Issue by zach-hartwig** [ipython-contrib/IPython-notebook-extensions#149]
Hey,

I'm really enjoying the NB extensions ... keep up the great work. I had a potential issue/question with python-markdown (2.7 series, using most recent version in that branch). I figured I'd post here (not sure if this is the "appropriate" place.)

I'd like to have a Python string variable that contains a URL turn into a clickable link in Markdown. If the python cell contains:
```
  URL = "[Google](http://www.google.com)"
```

and the Markdown cell contains
```
  {{URL}}
```
The link is rendered in the Markdown cell as:
```
  'Google'
```

but when I click the link, it asks to close the current Notebook page rather than opening Google in a new tab (If I put the raw markdown in the cell with no "{{}}"" then clicking 'Google' DOES open in a new tab as expected). Also the single quotes around the string also seem wrong. I'd like to just have the word appear as a hyperlink, if possible.

I notice in the python-markdown.js code that it appears that a "_blank" value is attached to the HTML target key (Line 106), but this doesn't seem to work. I'm not a javascript expert so rather than monkey around I thought I'd ask. Hopefully it's something simply I'm doing wrong.

Thanks for any help, and, again, I appreciate the effort.

~Zach

**Comment by juhasch** [comment]
Should work now. If you still have issues please reopen the issue.

**Comment by zach-hartwig** [comment]
Hi Juergan,

I really appreciate the response. I'll try testing it later this week maybe and let you know if there are further issues.

~Zach
