### ISSUE TITLE
installation url in wiki is wrong

### ISSUE THREAD

**Issue by jason-s** [ipython-contrib/IPython-notebook-extensions#166]
https://github.com/ipython-contrib/IPython-notebook-extensions/wiki#slidemode
```
import IPython
IPython.html.nbextensions.install_nbextension('https://rawgithub.com/minrk/ipython_extensions/master/nbextensions/gist.js')
```

please point to the ipython-contrib repo instead

**Comment by Carreau** [comment]
Not sure what you ask exactly, but if it's on the wiki you should be able to edit it; it is public.

**Comment by jason-s** [comment]
I would, but I don't know what the right URL is. The one listed is `http://rawgithub.com/minrk/...` but that's someone's private github account, and the wiki should be pointing to somewhere in `http://github.com/ipython-contrib`

**Comment by juhasch** [comment]
Unfortunately there is no documentation for the slidemode extension. What you see is an general example of how to install a notebook extension.

I don't know anything about the slidemode extension.

**Comment by jason-s** [comment]
?????? Please reopen! I didn't ask about documenting the slidemode extension here. I asked to point to the ipython-contrib repo (here) instead of the minrk account. This is the appropriate repository to link to. I don't know what the URL should be. If someone can just tell me, I would be happy to edit the wiki.

**Comment by juhasch** [comment]
Not sure what you mean. The URL is just an example. In your case it would be 
'https://raw.githubusercontent.com/ipython-contrib/IPython-notebook-extensions/master/slidemode/main.js'. Feel free to edit the Wiki if you think this is clearer.
