### ISSUE TITLE
Problems with hierarchical collapse

### ISSUE THREAD

**Issue by jat255** [ipython-contrib/IPython-notebook-extensions#168]
Hello, I am using hierarchical collapse on some of my notebooks, and the experience has been less than stellar than me so far. The behavior is very hard to document, as I cannot identify patterns to it, but I was hoping that someone might have experienced similar behavior and had some idea of how to correct it.

The gist of the issue is that the folding is not always as expected in my notebooks. For example, if I have a structure like the following:

    Heading 1
    |----Heading 2.1
    |----Heading 2.2
    |----Heading 2.3
        Markdown cell 1
        |----Heading 3.1
            Markdown cell 2
            Other cells
            .
            .
            .

When I click to collapse `Heading 2.3`, I would expect that it would collapse everything underneath it (both markdown cells, `Heading 3.1`, and all the other cells). Instead, it collapses `Markdown cell 1`, and `Heading 3.1`, but nothing else.

If I collapse `Heading 3.1` first, then it works as expected, but it seems as though it should work by collapsing _everything_ under the current header, regardless of the hidden status of the things underneath it.

This has led to more serious issues where I 'lose' cells if I have a complicated structure. I have a structure something like the following. Often times, when adding or deleting cells, or cutting and pasting, some sort of random folding will occur, and I can no longer find cells containing lots of code. If I search through the file (using keyboard navigation), it navigates through the hidden cells, and sometimes I can get them back by changing the heading level again, or cutting and pasting, but it doesn't always work, and it has caused me to lose work! 

    Heading 2.1
        Heading 3.1
            Heading 4.1
                Various cells of code and markdown
            Heading 4.2
                Various cells of code and markdown
            Heading 4.3
                Various cells of code and markdown
        Heading 3.2
            Heading 4.4
                Various cells of code and markdown
            Heading 4.5
                Various cells of code and markdown
            Heading 4.6
                Various cells of code and markdown

Does anyone have any experience with this? And is there any active development on this extension? It is in the testing directory, but hasn't seen a new commit in over 7 months. I would help, but I know next to nothing about javascript.

**Comment by jat255** [comment]
Sorry, should have noted my python/ipython info. I'm using a clean version of the 2.X branch.

$ python -c 'import IPython;print(IPython.sys_info())'
{'commit_hash': '948d8fc',
 'commit_source': 'installation',
 'default_encoding': 'cp437',
 'ipython_path': 'c:\\Python27\\lib\\site-packages\\IPython',
 'ipython_version': '2.3.1',
 'os_name': 'nt',
 'platform': 'Windows-8-6.2.9200',
 'sys_executable': 'c:\\Python27\\python.exe',
 'sys_platform': 'win32',
 'sys_version': '2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]'}

**Comment by juhasch** [comment]
The difficulty is that it is a complex extension and the author has not been not responding to questions for a while. So basically you are on your own figuring out how this extension works.

**Comment by juhasch** [comment]
Extension replaced by collapsible_headings
