### ISSUE TITLE
How to install hierarchical collapse extension

### ISSUE THREAD

**Issue by gabrielelanaro** [ipython-contrib/IPython-notebook-extensions#186]
I can't find anywhere on how to install this extension. If someone gives me a pointer I can volounteer to write the instructions on the wiki

**Comment by Aradan** [comment]
Hi, you can clone the repository in `.ipython/nbextensions` and add this at the end of your `profile_default/static/custom/custom.js` file:

```
// activate extensions only after Notebook is initialized
require(["base/js/events"], function (events) {
$([IPython.events]).on("app_initialized.NotebookApp", function () {
    /* load your extension here */
    IPython.load_extensions('hierarchical_collapse/main');
    });
});
```
