### ISSUE TITLE
FontAwesome icons depracated and need updating

### ISSUE THREAD

**Issue by zach-hartwig** [ipython-contrib/IPython-notebook-extensions#187]
Hello,

I've just cloned the most recent commit. I'm using the 'hide_input_all.js' and 'read-only.js' extensions, which work great. However, the icons for these extensions show up blank on my IPython Notebook It appears that the icon names need to be updated to FontAwesome4.2.0. For example, in 'read-only'.js, the current code attempts to specify a lock icon with:
```python
icon : 'icon-lock',
```
when for FontAwesome 4.2.0 it should be
```python
icon : 'fa-lock',
```
Making this change gets the icon working perfectly. I only use these two icon-based extensions presently, but, in general, all icons may need updating.

**Comment by juhasch** [comment]
Yes, this has been changed in IPython. Can you make a pull request with the required changes ?
