### ISSUE TITLE
usability/shift-tab does not exist.

### ISSUE THREAD

**Issue by Spaxe** [ipython-contrib/IPython-notebook-extensions#189]
I was looking for a way to add `shift-tab` into my personal config, and found:

https://github.com/ipython-contrib/IPython-notebook-extensions/wiki/Shift-tab

The repo suggests to copy `usability/shift-tab`, but it doesn't seem to exist anymore. Can someone enlighten?

**Comment by Carreau** [comment]
Git has this awesome power which allow you to still see the code ! 

https://github.com/ipython-contrib/IPython-notebook-extensions/pull/185/files

Will be of help ! Will fix wiki.

**Comment by Spaxe** [comment]
Thanks but ... why was the file removed?

**Comment by juhasch** [comment]
As stated in the Wiki, this extension is no longer useful for IPython 3.x.
`shift-tab` now works out of the box due to https://github.com/ipython-contrib/IPython-notebook-extensions/pull/185

The extension is still available in the 2.x repository.

**Comment by Spaxe** [comment]
Thanks. I checked out the repo and then the `2.x` branch, which will do for now. When `pip` get the next update I can then remove my little custom script. `:]`
