### ISSUE TITLE
Request: an extension that shows a ruler at 78th column in IPython Notebook

### ISSUE THREAD

**Issue by d33tah** [ipython-contrib/IPython-notebook-extensions#192]
As the title says, I would like to request an extension that shows a ruler at 78th column in IPython Notebook. @Carreau pointed me to this repository in [this IPython issue](https://github.com/ipython/ipython/issues/3165),

**Comment by juhasch** [comment]
You might try to modify this gist:
https://gist.github.com/juhasch/ea56dc964638933aa6a9

This will add rulers to all codecell based on the demo here:
http://codemirror.net/demo/rulers.html

**Comment by juhasch** [comment]
Just to add: I am currently too busy to do more.

**Comment by HyperionAnalytics** [comment]
I've tried patching junasch's code into custom.css, but haven't gotten it to work yet:

```javascript
require([
    'base/js/namespace',
    'base/js/events',
    'components/codemirror/lib/codemirror',
    'components/codemirror/addon/display/rulers'
], function(IPython, events, codemirror, rulers) {
    events.on('app_initialized.NotebookApp', function() {

    var column_num = 80;
    var color_code = "#DF0101";
    var rulers = ({color: color_code, column: column_num, lineStyle: "solid", width: 5});

    var createCell = function (event, nbcell) {
        var cell = nbcell.cell;
        if ((cell instanceof IPython.CodeCell)) {
            cell.code_mirror.setOption('rulers', rulers);
        }
    };

    var cells = IPython.notebook.get_cells();
    for (var i in cells) {
        var cell = cells[i];
        if ((cell instanceof IPython.CodeCell)) {
            cell.code_mirror.setOption('rulers', rulers);
        }
    }

     events.on('create.Cell', createCell);

    });
})
```

**Comment by juhasch** [comment]
You might want to put it in your `custom.js` and also try
`` 
var rulers = [{color: color_code, column: column_num, lineStyle: "solid", width: 5}];
```

**Comment by HyperionAnalytics** [comment]
Juergen, I owe you an apology. I misspelled your handle and file name. The code above was put into custom.js. I changed the post to reflect this.

**Comment by juhasch** [comment]
Does ist work now ?

**Comment by HyperionAnalytics** [comment]
No, it does not work. I dumped ipython notebook v.3 which is broken in so many ways that even devs have no answers.

So in  ipython notebook v.2 it kind of works. Newly created cells have a ruler, but the ruler does not persist after opening a notebook which was saved with rulers present in code cells. Here's what I got:
* In `~/.ipython/nbextensions/ruler.js`
```javascript
require(['/static/components/codemirror/addon/display/rulers.js']);
```
* In `~/.ipython/profile_default/custom.js`
```javascript
$([IPython.events]).on('app_initialized.NotebookApp', function () {

    IPython.load_extensions('ruler');

    var ruler = [{column: 79}];

    IPython.CodeCell.options_default.cm_config.rulers = ruler;

});
```
* In `~/.ipython/profile_default/custom.css`
```css
.CodeMirror-vscrollbar{display: none !important;}
.CodeMirror-ruler {border-left: 2px dashed green;} /* Custom ruler styling */
```

**Comment by HyperionAnalytics** [comment]
Found solution! Works in ipython notebook v.2, will check v.3 tomorrow, gotta get some sleep.

In  ipython notebook v.2:
* In `~/.ipython/profile_default/custom.js`
```javascript
$([IPython.events]).on('edit_mode.Cell', function (event, data) {

    function setRulers(cm) {
        var val = cm.getOption('rulers');
        var cw = cm.defaultCharWidth();
        var left = cm.charCoords(CodeMirror.Pos(cm.firstLine(), 0), 'div').left;
        var bot = -cm.display.scroller.offsetHeight;
        for (var i = 0; i < val.length; i++) {
            var elt = document.createElement('div');
            var col, cls = null;
            if (typeof val[i] == 'number') {
                col = val[i];
            } else {
                col = val[i].column;
                cls = val[i].className;
            }
            elt.className = 'CodeMirror-ruler' + (cls ? ' ' + cls : '');
            elt.style.cssText = 'left: ' + (left + col * cw) + 'px; top: -50px; bottom: ' + bot + 'px';
            cm.display.lineSpace.insertBefore(elt, cm.display.cursorDiv);
         }
    }

    var ruler = [{column: 79}];

    selected_cell = IPython.notebook.get_selected_cell();
    if ((selected_cell instanceof IPython.CodeCell)) {
        var cm = selected_cell.code_mirror;
        cm.setOption('rulers', ruler);
        setRulers(cm);
    }
});
```
* In `~/.ipython/profile_default/custom.css`
```css
.CodeMirror-vscrollbar{display: none !important;}
.CodeMirror-ruler {border-left: 1px solid #cccccc;} /* Custom ruler styling */
```

**Comment by damianavila** [comment]
PR welcome!!!

**Comment by jpeacock29** [comment]
To clarify, this extension now exists in [jupyter_contrib_nbextensions](https://github.com/ipython-contrib/jupyter_contrib_nbextensions) as the [Ruler](https://github.com/ipython-contrib/jupyter_contrib_nbextensions/tree/master/src/jupyter_contrib_nbextensions/nbextensions/ruler) extension.
