### ISSUE TITLE
Notebook Extension Config not loading

### ISSUE THREAD

**Issue by pylang** [ipython-contrib/IPython-notebook-extensions#199]
I followed [these instructions](https://github.com/ipython-contrib/IPython-notebook-extensions/wiki/config-extension) but localhost:8888/nbextensions says 404: Not Found.  I don't see anything being served in the prompt.  Any ideas?

Also, I think readme needs to be updated.  `c.NotebookApp.server_extensions = [ 'nbextensions', 'preview' ]` gives me a module ImportError.  Rather, I used code in the latest IPython_notebook_config.py file from the config folder and it removed the error. 

[Win7, python 2 (default), python 3 (virtualenv), IPython 3, nbextensions (master)]

**Comment by juhasch** [comment]
Thanks for the feedback. Did you try `localhost:8888/nbextensions/`including the trailing slash ?
I updated the description in the Wiki and removed the wrong `preview` entry.

**Comment by pylang** [comment]
Aha!  Works. Thanks.
