### ISSUE TITLE
config extension does not work with base_url

### ISSUE THREAD

**Issue by mcarans** [ipython-contrib/IPython-notebook-extensions#200]
When I set a base_url in ipython_notebook_config.py eg. c.NotebookApp.base_url = '/ipython/', then the nbextensions will not load (even if I go to /ipython/nbextensions/).

I can hard code a fix in nbextensions.html as follows:
<script src="{{ "/ipython/nbextensions/config/main.js" }}" type="text/javascript" charset="utf-8"></script>

This needs a proper fix that uses the base url.

**Comment by juhasch** [comment]
I will update this when I have more time. Feel free to submit a pull request yourself.

**Comment by juhasch** [comment]
Should be fixed. Is this still not working ?

**Comment by jcb91** [comment]
This should be fixed by #402, #403, I think?
