### ISSUE TITLE
Codefolding not working

### ISSUE THREAD

**Issue by denfromufa** [ipython-contrib/IPython-notebook-extensions#205]
How do I verify that codefolding installed properly, since it is not working? Alt-F is assigned to Chrome keys.

**Comment by juhasch** [comment]
You will se a gutter on the left side of a code cell:
https://github.com/ipython-contrib/IPython-notebook-extensions/wiki/Codefolding_v3
If not, check the Javascript console of your browser.

I never use Alt-F, as adding hotkeys is a mess.

**Comment by Tangent-Lin** [comment]
> You will se a gutter on the left side of a code cell: https://github.com/ipython-contrib/IPython-notebook-extensions/wiki/Codefolding_v3 If not, check the Javascript console of your browser.
> 
> I never use Alt-F, as adding hotkeys is a mess.
6 years passed , and  the hotkeys Alt + F  still not working in the Chrome v87 !
Why not just deleted the hotkeys documents content to end the users' searching work .
Or just raised the difficult details  of the hotkey adding to codefolding ?
