### ISSUE TITLE
Code folding on cell magics (e.g. %%file)

### ISSUE THREAD

**Issue by brazilbean** [ipython-contrib/IPython-notebook-extensions#206]
It would be great to have code folding on cells beginning with a cell magic, just as cells beginning with comments can be folded. 

Cell magics must always appear on the first line, so cells with a cell magic cannot have a comment header. However, because cell magics use a special character ('%'), perhaps folding can be activated for both '%' and '#'?

**Comment by juhasch** [comment]
This is easy to implement as additional folding mode. See PR #207

**Comment by juhasch** [comment]
Closed by #207
