### ISSUE TITLE
Extension Installation issues (multiple) on IPython 3.1.0

### ISSUE THREAD

**Issue by dartdog** [ipython-contrib/IPython-notebook-extensions#213]
sorry for this noise but I hope it might help...
I’m using IPython 3.1.0-dev 
I’ve been working with installing the IPython-notebook-extensions
I have run into numerous issues, some of which I have worked through and some not.
Normally I’d try to open specific one by one issues but in this case I think this format may be better?

The doc in the wiki incorrectly refers to IPython-notebook-extensions-3.x as a directory name. It should be IPython-notebook-extensions. unless the helper function works (not for me)
There is a helper function in IPython that will do this automatically for you:
import IPython.html.nbextensions as nb
ext= 'https://github.com/ipython-contrib/IPython-notebook-extensions/archive/3.x.zip'
nb.install_nbextension(ext)
This command fails with a security error Permission denied: '/usr/local/share/jupyter'
I don’t see a way to run sudo for this.

The python-markdown extension suggest modifying ipython_nbconvert_config.py which I cannot locate. It also suggests In order to have nbconvert show the preprocessed output, copy thepymdpreprocessor.py file to a location in your PYTHONPATH however if my path has '/home/tom/ipython/IPython/extensions' is this not suffecient? 

I was completely unable to get the graphical config working:
Instructions:
Add the following lines to your 'ipython_notebook_config.py' file (inside your profile directory, e.g. ~/.ipython/profile_default/): 

I have no ipython_notebook_config.py file….?

So.. since this does not work, I cloned the branch repo and placed it in both the /home/tom/ipython/IPython/extensions and /home/tom/.ipython/nbextensions

Surely only one of those is right!

I have gotten Python Markdown running and Hide input going in the notebook (the doc refers to hide_input_all which does not seem to exist which is fine by me) but can't get the nbconvert to incorporate for printing (export to Latex)

**Comment by dartdog** [comment]
Slowly, I have worked through it all or at least mostly. Some of the comments may or may not help someone to clarify the docs? I'm not quite up to it...

**Comment by alvinwt** [comment]
I found that using nb.install_nbextension(ext,user=True) helps with that permission denied error. This installs to the user's local dir instead of system wide in usr/shared/juypter
