### ISSUE TITLE
There is a mistake in custom.example.js

### ISSUE THREAD

**Issue by xtotdam** [ipython-contrib/IPython-notebook-extensions#215]
Line 34
`//    IPython.load_extensions('usability/codefolding/codefolding')`
should be
`//    IPython.load_extensions('usability/codefolding/main')`
as is written [there](https://github.com/ipython-contrib/IPython-notebook-extensions/wiki/Codefolding)

**Comment by xtotdam** [comment]
Just looked into 3.x branch, and it is already fixed.
Sorry

**Comment by Carreau** [comment]
No harm done. Thanks !

**Comment by xtotdam** [comment]
It was actually a bit confusing, that `master` branch is a bit old, compared to `3.x` :)
