### ISSUE TITLE
runtools: cannot see what cells are marked or not

### ISSUE THREAD

**Issue by triccare** [ipython-contrib/IPython-notebook-extensions#216]
With python 2.7.9, ipython 3.1.0, and master of this repo, everything works, i.e. running of marked cells, etc.. However, I cannot actually see which cells have been marked. There is no "gutter" that is mentioned.  Below is a screen capture along with the javascript console.

![screen shot 2015-05-11 at 4 57 03 pm](https://cloud.githubusercontent.com/assets/791636/7574915/df60f330-f7fe-11e4-93dc-4fe01e23c368.png)

**Comment by juhasch** [comment]
Currently you need to have the code folding extension enabled too, to see the gutter (the part where you mark cells). I plan to change this when I have more time.

**Comment by juhasch** [comment]
Fixed for Jupyter/IPython 4.x by #257

**Comment by triccare** [comment]
Nice! Thanks!
