### ISSUE TITLE
python-markdown.js works in the browser but not in nbcovert output

### ISSUE THREAD

**Issue by bgbg** [ipython-contrib/IPython-notebook-extensions#217]
I have installed `python-markdown.js` for IPython2 (my version is 2.4.0). I configured the `custom.js` file as described by the documentation. When I work with the notebook, everything works as expected. However, when I try to `nbconvert` the notebook, the resulting HTML file shows only the raw code, not the formatted output, despite the fact that everything runs without any errors:

    my-dir$ ipython2 nbconvert --to=html Untitled0.ipynb
    [NbConvertApp] Using existing profile dir: u'/Users/be/.ipython/profile_default'
    [NbConvertApp] Converting notebook Untitled0.ipynb to html
    [NbConvertApp] Support files will be in Untitled0_files/
    [NbConvertApp] Loaded template full.tpl
    [NbConvertApp] Writing 185954 bytes to Untitled0.html

**Comment by madtocc** [comment]
I was trying the markdown today and I also noticed it: it only print the variable not its content. I hope they have a fix for this, it would be perfect.

**Comment by juhasch** [comment]
You need to tell nbconvert to use the preprocessor from `pymdpreprocessor.py`. This will replace the code with the evaluated contents.
I'm busy right now so can't help you much nore for now.

**Comment by juhasch** [comment]
Did you get nbconvert working with python-markdown ?

**Comment by juhasch** [comment]
Closing.
