### ISSUE TITLE
Problem in codefolding: can not fold completely.

### ISSUE THREAD

**Issue by yifangma** [ipython-contrib/IPython-notebook-extensions#221]
When i use code folding in Jupyter, some cells can not be folded, and i did not find any grammar errors in these cells.

**Comment by psychemedia** [comment]
I've just tried installing the codefolding extension and I don't see any codefolding (recent Jupyter install, on a Mac, using chrome)? Notes suggest I maybe need to update Codemirror? Is this still the case or do I have another issue? Is there a simple instruction list for updating Codemirror for use by Jupyter server?

**Comment by yifangma** [comment]
![20150619135724](https://cloud.githubusercontent.com/assets/12451403/8259608/c93ffb7c-168b-11e5-8cfb-dadf9387daf1.png)

**Comment by juhasch** [comment]
Works for me with current Jupyter on Mac with Chrome. Do you get any error messages on the Javascript console output ?

**Comment by yifangma** [comment]
I reinstalled the Jupyter and the problem disappeared, thank you all.

And another small problem is the Css still dose not work, the option menu only has default option.
