### ISSUE TITLE
A way to freeze rendered Markdown cells?

### ISSUE THREAD

**Issue by rtrochet** [ipython-contrib/IPython-notebook-extensions#227]
I am using IPython 3.1.0 and mostly run Julia notebooks. I have installed the ReadOnly extension and modified it to lock Markdown cells, but they can still be unrendered by double-clicking. Is there a way to lock Markdown cells to keep them from being unrendered?

I am running some JavaScript (similar to https://gist.github.com/juhasch/2332190e19eb6276bed3) on the Markdown cells that I'd like to lock, and unrendering those cells undoes the effects of the JavaScript.

Thank you in advance for any guidance you can give me.

**Comment by juhasch** [comment]
There is no "official" way to do this.

You could override the `unrender` function in your `custom.js` to permanently disable editing:
```javascript
define(['notebook/js/cell'], function(cell) {
    "use strict";
	var old = cell.Cell.prototype.unrender;
	cell.Cell.prototype.unrender = function() {}
});
```

**Comment by rtrochet** [comment]
Thank you! That's exactly what I need.
