### ISSUE TITLE
main.js instead of python-markdown.js filename on github

### ISSUE THREAD

**Issue by marcomayer** [ipython-contrib/IPython-notebook-extensions#228]
In the wiki, the main script is called python-markdown.js which I think is correct but on github it's ttps://raw.githubusercontent.com/ipython-contrib/IPython-notebook-extensions/master/usability/python-markdown/main.js so you have to rename main.js first.

It also makes it hard to find the file. I was searching for python-markdown.js and couldn't find it. A link to the files in the wiki for the 2.x and the 3.x version would be very helpful too.

Thanks for your work!

Marco

**Comment by juhasch** [comment]
Thanks. I renamed it to `main.js` in the Wiki for 3.x.
