### ISSUE TITLE
How can I convert extension result to HTML or Printview?

### ISSUE THREAD

**Issue by choies1** [ipython-contrib/IPython-notebook-extensions#229]
When I use IPython-notebook-extensions, it works well on IPython Screen as Follows:

![image](https://cloud.githubusercontent.com/assets/10408785/8635951/bc49b188-287e-11e5-97dc-6c1ed03e482d.png)

However, when I press 'printview button', I only see the original result (not applying Extension) as follwows:

![image](https://cloud.githubusercontent.com/assets/10408785/8635956/cf1d68c2-287e-11e5-8cd7-be0bf1c39d06.png)

Is the any method to make printview to print results shown after applying IPython-notebook-extensions?

Or is there any plan to make extension having this function?

**Comment by juhasch** [comment]
As described in the Wiki [here](https://github.com/ipython-contrib/IPython-notebook-extensions/wiki/python-markdown_v3), you need to add a preprocessor for nbconvert.
This can by done by adding this line to the `ipython_nbconvert_config.py`file:
`c.Exporter.preprocessors = [ 'pymdpreprocessor.PyMarkdownPreprocessor' ]`

**Comment by choies1** [comment]
Thanks to your comment, I succeeded.

1. copy 'pymdpreprocessor.py' to python path (or, PYTHONPATH).
2. copy 'ipython_nbconvert_config.py' to 'C:\Users\login_ID\.ipython\profile_default', and edit it as follows:

```
c = get_config()

c.NbConvertApp.notebooks = ['*.ipynb']
c.Exporter.preprocessors = ['pymdpreprocessor.PyMarkdownPreprocessor']
```

Printview result is as follows.

![image](https://cloud.githubusercontent.com/assets/10408785/8637854/ca9afa82-28e0-11e5-9628-886d9ec5df87.png)

**Comment by juhasch** [comment]
Thanks for the feedback.
