### ISSUE TITLE
exercise extension - bad path

### ISSUE THREAD

**Issue by psychemedia** [ipython-contrib/IPython-notebook-extensions#234]
The `exercise` extension contains an incorrect path:

    load_css('/nbextensions/testing/exercise/main.css');

should be:

    load_css('/nbextensions/exercise/main.css');

I can't work out how to use this extension? Is it still in testing/incomplete? Looks like it could be really useful...

**Comment by psychemedia** [comment]
So  - progress. The *exercise* extension requires the *rubberband* extension, and seems to work partially:

1) the `main.css` file in the extension is not picked up - it seems as if the extension handler is looking to load from `localhost/nbextensions/usability/rubberband/main.css` and then 404ing
2) I can only set exercises where the first cell in the notebook is the first one looped by the rubberband. If I try to loop cells lower down the notebook, nothing happens when I click the *exercise*  `Hide solution` button.

**Comment by juhasch** [comment]
I have made a fix for the invalid path. Thanks for reporting.
The extension works for me, but the logic is a little brittle. It should probably have stayed in `testing`.
I intend to work on it in September, but feel free to play around with it.

Basically, the extension works by selecting a number of cells with the rubber band and then hiding all but the first cell. Clicking on the plus should show all cells again.

**Comment by psychemedia** [comment]
I have a demo in am `Exercises` notebook posted [here](http://blog.ouseful.info/2015/07/25/fighting-with-docker-and-pondering-innovation-in-an-institutional-context/).

One thing I found was that things seem a little brittle when trying to create  an *exercise* where the first cel is not the first cell in the notebook?

**Comment by jcb91** [comment]
This was (probably?) fixed by the updated exercises in #383

**Comment by nehebkau** [comment]
I like this extension but I have a problem. when I use twice (or more) Exercise 2 button, pressing the first button created, it hides all the buttons below. Is there any solution for this or am I doing something wrong?

**Comment by jfbercher** [comment]
If I understand well, this may be a consequence of what follows.  
Currently, the extension hides the series of consecutive cells that are marked (in their metadata) with solution2="hidden". If one creates two consecutive exercices, then they are "merged" by this mechanism - there is currently no test for detecting if a cell is the beginning of a new exercise. This should be implemented in some future. For now, you may simply separate the exercises by a non-exercise cell. Typically, I use an empty raw-cell.

**Comment by nehebkau** [comment]
This was exactly the problem. Thank you jfbercher.
