### ISSUE TITLE
404: Not Found Problem

### ISSUE THREAD

**Issue by ofenerci** [ipython-contrib/IPython-notebook-extensions#235]
Dear All,
I am trying to install graphical user interface for Jupyter notebook extensions described in https://github.com/ipython-contrib/IPython-notebook-extensions/wiki/config-extension.

I have installed the files but I am getting an error "404 : Not Found. You are requesting a page that does not exist!". 

There a few questions on which how to install this extensions:
1) In the installation directions, it says that the files need to be installed inside profile directory. When I give a command,
$jupyter --config
It gives "~/.jupyter". I wonder it could be a problem because in the installation instruction, the profile directory is given "./ipython". Actually I installed those files inside "~/.ipython" directory, but still same error. 

2)  'ipython_notebook_config.py" file given in installation procedure on github page is different from github repository. Which one should I use? In the github file, there is one extra line: "c.NotebookApp.open_browser = False".

P.S. I have been cautious to be about  " '/nbextensions/' URL (mind the trailing slash)" . I have used both chromium and iceweasel (in Debian testing). But nothing changed.

Best Regards,
Ozhan

**Comment by brunobeltran** [comment]
ofenercl, can you check the output of the Jupyter process? I recently had the same problem on Debian Jessie and it was simply due to the system having installed a version of some package (pyyaml I think?) that was way too old. 

Can you drop the output of "ipython notebook --debug" or "jupyter --debug" (whichever you're trying to run) here?

**Comment by juhasch** [comment]
I have updated the extensions and it now prints some information in the Python and the Javascript part.
My configuration file `jupyter_notebook_config.py` for Jupyter looks like this:
```Python
from jupyter_core.paths import jupyter_config_dir
import os
import sys

jupyterdir = jupyter_config_dir()
extensions = os.path.join(jupyterdir,'extensions') 
sys.path.append( extensions )

c = get_config()
c.NotebookApp.server_extensions = [ 'nbextensions' ]
c.NotebookApp.extra_template_paths = [os.path.join(jupyterdir,'templates') ]
```
The `nbextension.py` file is in `./jupyter/extensions`

**Comment by ofenerci** [comment]
Dear brunobeltran and juhasch,

After many hand-waving and installing jupyter by root,  I was able to solve my problem. I changed my configuration as juhasch's. I also installed jupyter by using " pip3  install --pre -e . " not by "pip install --pre -e." I also updated yaml by "pip3 install pyaml". 

Still there is a problem if I run the jupyter from "virtualenv" or by non-root user. When I run an install from virtualenv by "pip3 install --user --pre -e ." , it installs without any problem. When I try to reach the extensions's  page, I  get an blank page, not even "404 : Not Found" error. 

Here is the debug:
[D 13:41:49.707 NotebookApp] Config changed:
[D 13:41:49.707 NotebookApp] {'NotebookApp': {'log_level': 10}}
[D 13:41:49.707 NotebookApp] Searching [u'/home/ozhanfenerci/GitRepos/notebook', '/home/ozhanfenerci/.jupyter', '/home/ozhanfenerci/virtualenv/jupyter-notebook/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files
[D 13:41:49.707 NotebookApp] Attempting to load config file jupyter_config.py in path /etc/jupyter
[D 13:41:49.708 NotebookApp] Attempting to load config file jupyter_config.json in path /etc/jupyter
[D 13:41:49.708 NotebookApp] Attempting to load config file jupyter_config.py in path /usr/local/etc/jupyter
[D 13:41:49.708 NotebookApp] Attempting to load config file jupyter_config.json in path /usr/local/etc/jupyter
[D 13:41:49.708 NotebookApp] Attempting to load config file jupyter_config.py in path /home/ozhanfenerci/virtualenv/jupyter-notebook/etc/jupyter
[D 13:41:49.708 NotebookApp] Attempting to load config file jupyter_config.json in path /home/ozhanfenerci/virtualenv/jupyter-notebook/etc/jupyter
[D 13:41:49.708 NotebookApp] Attempting to load config file jupyter_config.py in path /home/ozhanfenerci/.jupyter
[D 13:41:49.708 NotebookApp] Attempting to load config file jupyter_config.json in path /home/ozhanfenerci/.jupyter
[D 13:41:49.708 NotebookApp] Attempting to load config file jupyter_config.py in path /home/ozhanfenerci/GitRepos/notebook
[D 13:41:49.708 NotebookApp] Attempting to load config file jupyter_config.json in path /home/ozhanfenerci/GitRepos/notebook
[D 13:41:49.708 NotebookApp] Attempting to load config file jupyter_notebook_config.py in path /etc/jupyter
[D 13:41:49.709 NotebookApp] Attempting to load config file jupyter_notebook_config.json in path /etc/jupyter
[D 13:41:49.709 NotebookApp] Attempting to load config file jupyter_notebook_config.py in path /usr/local/etc/jupyter
[D 13:41:49.709 NotebookApp] Attempting to load config file jupyter_notebook_config.json in path /usr/local/etc/jupyter
[D 13:41:49.709 NotebookApp] Attempting to load config file jupyter_notebook_config.py in path /home/ozhanfenerci/virtualenv/jupyter-notebook/etc/jupyter
[D 13:41:49.709 NotebookApp] Attempting to load config file jupyter_notebook_config.json in path /home/ozhanfenerci/virtualenv/jupyter-notebook/etc/jupyter
[D 13:41:49.709 NotebookApp] Attempting to load config file jupyter_notebook_config.py in path /home/ozhanfenerci/.jupyter
[D 13:41:49.709 NotebookApp] Attempting to load config file jupyter_notebook_config.json in path /home/ozhanfenerci/.jupyter
[D 13:41:49.710 NotebookApp] Loaded config file: /home/ozhanfenerci/.jupyter/jupyter_notebook_config.py
[D 13:41:49.710 NotebookApp] Config changed:
[D 13:41:49.710 NotebookApp] {'NotebookApp': {'server_extensions': ['nbextensions'], 'log_level': 10, 'extra_template_paths': ['/home/ozhanfenerci/.jupyter/templates']}}
[D 13:41:49.711 NotebookApp] Config changed:
[D 13:41:49.711 NotebookApp] {'NotebookApp': {'server_extensions': ['nbextensions'], 'log_level': 10, 'extra_template_paths': ['/home/ozhanfenerci/.jupyter/templates']}}
[D 13:41:49.711 NotebookApp] Attempting to load config file jupyter_notebook_config.py in path /home/ozhanfenerci/GitRepos/notebook
[D 13:41:49.711 NotebookApp] Attempting to load config file jupyter_notebook_config.json in path /home/ozhanfenerci/GitRepos/notebook
[D 13:41:49.711 NotebookApp] Config changed:
[D 13:41:49.712 NotebookApp] {'NotebookApp': {'server_extensions': ['nbextensions'], 'log_level': 10, 'extra_template_paths': ['/home/ozhanfenerci/.jupyter/templates']}}
[W 13:41:49.729 NotebookApp] ipywidgets package not installed.  Widgets are unavailable.
[I 13:41:49.756 NotebookApp] Serving notebooks from local directory: /home/ozhanfenerci/GitRepos/notebook
[I 13:41:49.756 NotebookApp] 0 active kernels 
[I 13:41:49.756 NotebookApp] The IPython Notebook is running at: http://localhost:8888/
[I 13:41:49.756 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).

(process:20110): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed
[D 13:41:49.865 NotebookApp] Using contents: services/contents
[D 13:41:49.901 NotebookApp] 200 GET /tree (::1) 38.39ms
[D 13:41:49.940 NotebookApp] 200 GET /custom/custom.css (::1) 3.85ms
[D 13:41:50.100 NotebookApp] 200 GET /static/services/contents.js (::1) 0.81ms
[D 13:41:50.104 NotebookApp] 200 GET /custom/custom.js (::1) 0.80ms
[D 13:41:50.137 NotebookApp] 200 GET /api/config/tree?_=1438425710034 (::1) 1.05ms
[D 13:41:50.140 NotebookApp] 200 GET /api/config/common?_=1438425710035 (::1) 0.94ms
[D 13:41:50.148 NotebookApp] 200 GET /api/terminals?_=1438425710036 (::1) 1.27ms
[D 13:41:50.152 NotebookApp] Found kernel octave_kernel in /usr/local/share/jupyter/kernels
[D 13:41:50.153 NotebookApp] Found kernel ir in /usr/local/share/jupyter/kernels
[D 13:41:50.153 NotebookApp] Found kernel bash in /usr/local/share/jupyter/kernels
[D 13:41:50.153 NotebookApp] Found kernel python3 in /usr/local/share/jupyter/kernels
[D 13:41:50.153 NotebookApp] Found kernel python2 in /usr/local/share/jupyter/kernels
[D 13:41:50.153 NotebookApp] Found kernel octave_kernel in /usr/local/share/jupyter/kernels
[D 13:41:50.154 NotebookApp] Found kernel ir in /usr/local/share/jupyter/kernels
[D 13:41:50.154 NotebookApp] Found kernel bash in /usr/local/share/jupyter/kernels
[D 13:41:50.154 NotebookApp] Found kernel python3 in /usr/local/share/jupyter/kernels
[D 13:41:50.154 NotebookApp] Found kernel python2 in /usr/local/share/jupyter/kernels
[D 13:41:50.155 NotebookApp] Found kernel octave_kernel in /usr/local/share/jupyter/kernels
[D 13:41:50.155 NotebookApp] Found kernel ir in /usr/local/share/jupyter/kernels
[D 13:41:50.156 NotebookApp] Found kernel bash in /usr/local/share/jupyter/kernels
[D 13:41:50.157 NotebookApp] Found kernel python3 in /usr/local/share/jupyter/kernels
[D 13:41:50.157 NotebookApp] Found kernel python2 in /usr/local/share/jupyter/kernels
[D 13:41:50.158 NotebookApp] Found kernel octave_kernel in /usr/local/share/jupyter/kernels
[D 13:41:50.158 NotebookApp] Found kernel ir in /usr/local/share/jupyter/kernels
[D 13:41:50.159 NotebookApp] Found kernel bash in /usr/local/share/jupyter/kernels
[D 13:41:50.159 NotebookApp] Found kernel python3 in /usr/local/share/jupyter/kernels
[D 13:41:50.159 NotebookApp] Found kernel python2 in /usr/local/share/jupyter/kernels
[D 13:41:50.160 NotebookApp] Found kernel octave_kernel in /usr/local/share/jupyter/kernels
[D 13:41:50.160 NotebookApp] Found kernel ir in /usr/local/share/jupyter/kernels
[D 13:41:50.160 NotebookApp] Found kernel bash in /usr/local/share/jupyter/kernels
[D 13:41:50.160 NotebookApp] Found kernel python3 in /usr/local/share/jupyter/kernels
[D 13:41:50.161 NotebookApp] Found kernel python2 in /usr/local/share/jupyter/kernels
[D 13:41:50.162 NotebookApp] Found kernel octave_kernel in /usr/local/share/jupyter/kernels
[D 13:41:50.162 NotebookApp] Found kernel ir in /usr/local/share/jupyter/kernels
[D 13:41:50.162 NotebookApp] Found kernel bash in /usr/local/share/jupyter/kernels
[D 13:41:50.162 NotebookApp] Found kernel python3 in /usr/local/share/jupyter/kernels
[D 13:41:50.162 NotebookApp] Found kernel python2 in /usr/local/share/jupyter/kernels
[D 13:41:50.165 NotebookApp] 200 GET /api/kernelspecs (::1) 14.10ms
[D 13:41:50.168 NotebookApp] 200 GET /api/terminals?_=1438425710038 (::1) 1.24ms
[D 13:41:50.170 NotebookApp] 200 GET /api/sessions?_=1438425710037 (::1) 2.07ms
[D 13:41:51.155 NotebookApp] 200 GET /api/contents?type=directory&_=1438425710039 (::1) 11.56ms
[D 13:42:00.455 NotebookApp] 200 GET /api/sessions?_=1438425710040 (::1) 1.03ms
[D 13:42:00.458 NotebookApp] 200 GET /api/terminals?_=1438425710041 (::1) 0.82ms
('/usr/local/share/jupyter/nbextensions', '/home/ozhanfenerci/.local/share/jupyter/nbextensions')
[D 13:42:00.531 NotebookApp] Using contents: services/contents
[D 13:42:00.535 NotebookApp] 200 GET /nbextensions/ (::1) 55.99ms
[D 13:42:00.557 NotebookApp] 200 GET /custom/custom.css (::1) 0.77ms
[D 13:42:00.561 NotebookApp] 200 GET /nbextensions/config/main.js (::1) 0.97ms
[D 13:42:00.615 NotebookApp] 200 GET /static/base/js/namespace.js (::1) 1.44ms
[D 13:42:00.617 NotebookApp] 200 GET /static/base/js/utils.js (::1) 1.32ms
[D 13:42:00.620 NotebookApp] 200 GET /static/base/js/page.js (::1) 1.26ms
[D 13:42:00.623 NotebookApp] 200 GET /static/components/jquery/jquery.min.js (::1) 1.87ms
[D 13:42:00.625 NotebookApp] 200 GET /static/services/contents.js (::1) 1.13ms
[D 13:42:00.626 NotebookApp] 200 GET /static/base/js/events.js (::1) 0.92ms
[D 13:42:00.628 NotebookApp] 200 GET /static/services/config.js (::1) 0.93ms
[D 13:42:00.647 NotebookApp] 200 GET /static/components/codemirror/lib/codemirror.js (::1) 1.63ms
[D 13:42:00.650 NotebookApp] 200 GET /static/components/moment/moment.js (::1) 1.60ms
[D 13:42:00.652 NotebookApp] 200 GET /static/components/codemirror/mode/meta.js (::1) 1.54ms




(jupyter-notebook)ozhanfenerci:notebook$jupyter-notebook --debug
[D 13:09:40.311 NotebookApp] Config changed:
[D 13:09:40.311 NotebookApp] {'NotebookApp': {'log_level': 10}}
[D 13:09:40.311 NotebookApp] Searching [u'/home/ozhanfenerci/GitRepos/notebook', '/home/ozhanfenerci/.jupyter', '/home/ozhanfenerci/virtualenv/jupyter-notebook/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files
[D 13:09:40.312 NotebookApp] Attempting to load config file jupyter_config.py in path /etc/jupyter
[D 13:09:40.312 NotebookApp] Attempting to load config file jupyter_config.json in path /etc/jupyter
[D 13:09:40.312 NotebookApp] Attempting to load config file jupyter_config.py in path /usr/local/etc/jupyter
[D 13:09:40.312 NotebookApp] Attempting to load config file jupyter_config.json in path /usr/local/etc/jupyter
[D 13:09:40.312 NotebookApp] Attempting to load config file jupyter_config.py in path /home/ozhanfenerci/virtualenv/jupyter-notebook/etc/jupyter
[D 13:09:40.312 NotebookApp] Attempting to load config file jupyter_config.json in path /home/ozhanfenerci/virtualenv/jupyter-notebook/etc/jupyter
[D 13:09:40.312 NotebookApp] Attempting to load config file jupyter_config.py in path /home/ozhanfenerci/.jupyter
[D 13:09:40.312 NotebookApp] Attempting to load config file jupyter_config.json in path /home/ozhanfenerci/.jupyter
[D 13:09:40.313 NotebookApp] Attempting to load config file jupyter_config.py in path /home/ozhanfenerci/GitRepos/notebook
[D 13:09:40.313 NotebookApp] Attempting to load config file jupyter_config.json in path /home/ozhanfenerci/GitRepos/notebook
[D 13:09:40.313 NotebookApp] Attempting to load config file jupyter_notebook_config.py in path /etc/jupyter
[D 13:09:40.313 NotebookApp] Attempting to load config file jupyter_notebook_config.json in path /etc/jupyter
[D 13:09:40.313 NotebookApp] Attempting to load config file jupyter_notebook_config.py in path /usr/local/etc/jupyter
[D 13:09:40.313 NotebookApp] Attempting to load config file jupyter_notebook_config.json in path /usr/local/etc/jupyter
[D 13:09:40.313 NotebookApp] Attempting to load config file jupyter_notebook_config.py in path /home/ozhanfenerci/virtualenv/jupyter-notebook/etc/jupyter
[D 13:09:40.313 NotebookApp] Attempting to load config file jupyter_notebook_config.json in path /home/ozhanfenerci/virtualenv/jupyter-notebook/etc/jupyter
[D 13:09:40.313 NotebookApp] Attempting to load config file jupyter_notebook_config.py in path /home/ozhanfenerci/.jupyter
[D 13:09:40.313 NotebookApp] Attempting to load config file jupyter_notebook_config.json in path /home/ozhanfenerci/.jupyter
[D 13:09:40.314 NotebookApp] Loaded config file: /home/ozhanfenerci/.jupyter/jupyter_notebook_config.py
[D 13:09:40.315 NotebookApp] Config changed:
[D 13:09:40.315 NotebookApp] {'NotebookApp': {'server_extensions': ['nbextensions'], 'log_level': 10, 'extra_template_paths': ['/home/ozhanfenerci/.jupyter/templates']}}
[D 13:09:40.315 NotebookApp] Config changed:
[D 13:09:40.315 NotebookApp] {'NotebookApp': {'server_extensions': ['nbextensions'], 'log_level': 10, 'extra_template_paths': ['/home/ozhanfenerci/.jupyter/templates']}}
[D 13:09:40.315 NotebookApp] Attempting to load config file jupyter_notebook_config.py in path /home/ozhanfenerci/GitRepos/notebook
[D 13:09:40.315 NotebookApp] Attempting to load config file jupyter_notebook_config.json in path /home/ozhanfenerci/GitRepos/notebook
[D 13:09:40.316 NotebookApp] Config changed:
[D 13:09:40.316 NotebookApp] {'NotebookApp': {'server_extensions': ['nbextensions'], 'log_level': 10, 'extra_template_paths': ['/home/ozhanfenerci/.jupyter/templates']}}
[W 13:09:40.332 NotebookApp] ipywidgets package not installed.  Widgets are unavailable.
[D 13:09:40.339 NotebookApp] Found kernel octave_kernel in /usr/local/share/jupyter/kernels
[D 13:09:40.339 NotebookApp] Found kernel ir in /usr/local/share/jupyter/kernels
[D 13:09:40.339 NotebookApp] Found kernel bash in /usr/local/share/jupyter/kernels
[D 13:09:40.339 NotebookApp] Found kernel python3 in /usr/local/share/jupyter/kernels
[D 13:09:40.339 NotebookApp] Found kernel python2 in /usr/local/share/jupyter/kernels
[I 13:09:40.362 NotebookApp] Serving notebooks from local directory: /home/ozhanfenerci/GitRepos/notebook
[I 13:09:40.362 NotebookApp] 0 active kernels 
[I 13:09:40.362 NotebookApp] The IPython Notebook is running at: http://localhost:8888/
[I 13:09:40.362 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).

(process:17571): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed
[D 13:09:40.458 NotebookApp] Using contents: services/contents
[D 13:09:40.497 NotebookApp] 304 GET /tree (::1) 41.66ms
[D 13:09:40.538 NotebookApp] 200 GET /custom/custom.css (::1) 4.82ms
[D 13:09:40.748 NotebookApp] 200 GET /static/services/contents.js (::1) 12.97ms
[D 13:09:40.751 NotebookApp] 200 GET /custom/custom.js (::1) 1.73ms
[D 13:09:40.781 NotebookApp] 200 GET /api/config/tree?_=1438423780666 (::1) 0.97ms
[D 13:09:40.789 NotebookApp] 200 GET /api/config/common?_=1438423780667 (::1) 0.79ms
[D 13:09:40.796 NotebookApp] 200 GET /api/terminals?_=1438423780668 (::1) 0.74ms
[D 13:09:40.804 NotebookApp] 200 GET /api/sessions?_=1438423780669 (::1) 1.24ms
[D 13:09:40.806 NotebookApp] 200 GET /api/terminals?_=1438423780670 (::1) 0.84ms
[D 13:09:40.826 NotebookApp] Found kernel octave_kernel in /usr/local/share/jupyter/kernels
[D 13:09:40.826 NotebookApp] Found kernel ir in /usr/local/share/jupyter/kernels
[D 13:09:40.827 NotebookApp] Found kernel bash in /usr/local/share/jupyter/kernels
[D 13:09:40.827 NotebookApp] Found kernel python3 in /usr/local/share/jupyter/kernels
[D 13:09:40.827 NotebookApp] Found kernel python2 in /usr/local/share/jupyter/kernels
[D 13:09:40.827 NotebookApp] Found kernel octave_kernel in /usr/local/share/jupyter/kernels
[D 13:09:40.827 NotebookApp] Found kernel ir in /usr/local/share/jupyter/kernels
[D 13:09:40.827 NotebookApp] Found kernel bash in /usr/local/share/jupyter/kernels
[D 13:09:40.828 NotebookApp] Found kernel python3 in /usr/local/share/jupyter/kernels
[D 13:09:40.828 NotebookApp] Found kernel python2 in /usr/local/share/jupyter/kernels
[D 13:09:40.829 NotebookApp] Found kernel octave_kernel in /usr/local/share/jupyter/kernels
[D 13:09:40.829 NotebookApp] Found kernel ir in /usr/local/share/jupyter/kernels
[D 13:09:40.829 NotebookApp] Found kernel bash in /usr/local/share/jupyter/kernels
[D 13:09:40.829 NotebookApp] Found kernel python3 in /usr/local/share/jupyter/kernels
[D 13:09:40.830 NotebookApp] Found kernel python2 in /usr/local/share/jupyter/kernels
[D 13:09:40.831 NotebookApp] Found kernel octave_kernel in /usr/local/share/jupyter/kernels
[D 13:09:40.831 NotebookApp] Found kernel ir in /usr/local/share/jupyter/kernels
[D 13:09:40.831 NotebookApp] Found kernel bash in /usr/local/share/jupyter/kernels
[D 13:09:40.831 NotebookApp] Found kernel python3 in /usr/local/share/jupyter/kernels
[D 13:09:40.831 NotebookApp] Found kernel python2 in /usr/local/share/jupyter/kernels
[D 13:09:40.832 NotebookApp] Found kernel octave_kernel in /usr/local/share/jupyter/kernels
[D 13:09:40.832 NotebookApp] Found kernel ir in /usr/local/share/jupyter/kernels
[D 13:09:40.832 NotebookApp] Found kernel bash in /usr/local/share/jupyter/kernels
[D 13:09:40.832 NotebookApp] Found kernel python3 in /usr/local/share/jupyter/kernels
[D 13:09:40.832 NotebookApp] Found kernel python2 in /usr/local/share/jupyter/kernels
[D 13:09:40.833 NotebookApp] Found kernel octave_kernel in /usr/local/share/jupyter/kernels
[D 13:09:40.833 NotebookApp] Found kernel ir in /usr/local/share/jupyter/kernels
[D 13:09:40.833 NotebookApp] Found kernel bash in /usr/local/share/jupyter/kernels
[D 13:09:40.833 NotebookApp] Found kernel python3 in /usr/local/share/jupyter/kernels
[D 13:09:40.834 NotebookApp] Found kernel python2 in /usr/local/share/jupyter/kernels
[D 13:09:40.835 NotebookApp] 304 GET /api/kernelspecs (::1) 9.40ms
[D 13:09:40.849 NotebookApp] 200 GET /api/contents?type=directory&_=1438423780671 (::1) 7.22ms
('/usr/local/share/jupyter/nbextensions', '/home/ozhanfenerci/.local/share/jupyter/nbextensions')
[D 13:09:50.561 NotebookApp] Using contents: services/contents
[D 13:09:50.565 NotebookApp] 304 GET /nbextensions/ (::1) 60.51ms
[D 13:09:50.592 NotebookApp] 200 GET /nbextensions/config/main.js (::1) 1.11ms
[D 13:09:50.617 NotebookApp] 304 GET /custom/custom.css (::1) 2.27ms
[D 13:09:50.723 NotebookApp] 200 GET /static/base/js/namespace.js (::1) 69.15ms
[D 13:09:50.736 NotebookApp] 200 GET /static/base/js/page.js (::1) 11.59ms
[D 13:09:50.747 NotebookApp] 200 GET /static/base/js/events.js (::1) 10.15ms
[D 13:09:50.763 NotebookApp] 200 GET /static/components/jquery/jquery.min.js (::1) 15.28ms
[D 13:09:50.778 NotebookApp] 200 GET /static/services/config.js (::1) 14.48ms
[D 13:09:50.784 NotebookApp] 200 GET /static/base/js/utils.js (::1) 4.52ms
[D 13:09:50.788 NotebookApp] 304 GET /static/services/contents.js (::1) 1.09ms
[D 13:09:50.815 NotebookApp] 200 GET /static/components/codemirror/lib/codemirror.js (::1) 13.36ms
[D 13:09:50.824 NotebookApp] 200 GET /static/components/moment/moment.js (::1) 7.91ms
[D 13:09:50.836 NotebookApp] 200 GET /static/components/codemirror/mode/meta.js (::1) 10.46ms

**Comment by juhasch** [comment]
Can you do a 'import nbextensions` in the notebook ?
This verifies IPython finds the server extension.

**Comment by ofenerci** [comment]
"import nbextensions" looks okey from either root or user account. Jupyter imports nbextensions. There is no harm running jupyter from my root account in which nbextensions' graphical interface works ok. I may need to read several times of installation and issues to figure out exactly how jupyter and its extension works. 

@juhasch, it is possible to update installation instructions for 4.x  to reflect the changes in jupyter. 

Thanks for very nice graphical interface.
Ozhan

**Comment by juhasch** [comment]
4.x is not released yet, so documenting a moving target does not make much sense, I believe.

**Comment by juhasch** [comment]
Documentation should be improved now thanks to @jcb91.
