### ISSUE TITLE
hierarchical_collapse of parent on deletion of any daughter cell

### ISSUE THREAD

**Issue by brunobeltran** [ipython-contrib/IPython-notebook-extensions#244]
On 3.x branch, IPython 3.2.1,

Say you have some cells in an implicit hierarchy like:

    Cell[0]--  Title1
    Cell[1]--    |-Title2
    Cell[2]--      |- some markdown
    Cell[3]--      |- some markdown
    Cell[4]--      |- some markdown
    Cell[5]--  Title1Again
    Cell[6]--   |- some markdown

The deletion of any of cells 2-4 will cause a collapse at Cell[1] (Title2) to be triggered. This is definitely not the expected behavior, and it is quite annoying to have to reopen the collapsed cell and scroll back to where I was if I want to e.g. delete multiple adjacent cells quickly.

I might have time to fix this after work, if it's as straightforward as I imagine.

**Comment by jcb91** [comment]
This doesn't happen with [`nbextensions/usability/collapsibe_headings`](https://github.com/ipython-contrib/IPython-notebook-extensions/tree/master/nbextensions/usability/collapsible_headings). Essentially, I gave up trying to fix all the bugs in hierarchical_collapse, and went for a complete rewrite as a simpler solution.

**Comment by jcb91** [comment]
`hierarchical_collapse` has been replaced by `collapsible_headings` in #507
