### ISSUE TITLE
setup.py tweaks

### ISSUE THREAD

**Issue by dfolch** [ipython-contrib/IPython-notebook-extensions#252]
I had to make some small changes to get setup.py to run on my machine.

from...
```
from notebook.nbextensions import install_nbextension
from notebook.services.config import ConfigManager
```
to...
```
from IPython.html.nbextensions import install_nbextension
from IPython.html.services.config.manager import ConfigManager
```
IPython version...
```
In [1]: import IPython

In [2]: IPython.__version__
Out[2]: '3.0.0'
```

**Comment by juhasch** [comment]
For IPython 3.x you need to use the 3.x branch. The master branch is for Jupyter/IPython 4.

**Comment by dfolch** [comment]
Sorry. This issue has to do with the notebook slides.  It should have been posted to the RISE folks.

**Comment by damianavila** [comment]
In RISE we have the same pattern, master is following Jupyter and you have a 3.x branch for IPython 3 versions :wink:
