### ISSUE TITLE
IPython.load_extension doesn't work due to relative path

### ISSUE THREAD

**Issue by aiguofer** [ipython-contrib/IPython-notebook-extensions#254]
I was unable to load some extensions and was able to trace it to this problem:

```
    var load_extensions = function () {
        // load one or more IPython notebook extensions with requirejs
        var extensions = [];
        var extension_names = arguments;
        for (var i = 0; i < extension_names.length; i++) {
            extensions.push("nbextensions/" + arguments[i]);
        }
    ...
```

This creates a relative path which means that whenever you run the function within a notebook, it tries to fetch from `<notebook_url>/nbextensions/<extension_path>` and, thus, can't find it.

I'm not very familiar with the extensions codebase, but it seems like it should be:
`extensions.push("/nbextensions/" + arguments[i]);` instead. If this is correct I could submit a PR, or maybe someone else can fix. Please also fix for 3.x branch which is what I'm using.

**Comment by juhasch** [comment]
Where is the code located you are citing ?
If it is from within IPython itself, please open an issue there: https://github.com/ipython/ipython
I am sure they will welcome a pull request that fixes wrong URL path construction.

This repo just holds a number of extensions and is not officially related to the IPython developers.

**Comment by aiguofer** [comment]
Oh right... lol I'm not sure what I was thinking when I created this.. obviously the code isn't even here :-P

Closing and adding there
