### ISSUE TITLE
mathjax sometimes not rendering when using python-markdown

### ISSUE THREAD

**Issue by maximerischard** [ipython-contrib/IPython-notebook-extensions#260]
When the markdown input cell is long and contains a lot of equations, the equations do not render while using python-markdown, even if there are no python-markdown `{{...}}` calls inside of the markdown cell. This stops happening if I disable the `python-markdown` extension. After spending half a day trying to track down what was happening, I noticed that when the input is short, at the moment the python-markdown `render_cell` function is triggered, `MathJax.Hub.queue.pending` is 0 and rendering works fine. When I add some more equations to the same cell, `MathJax.Hub.queue.pending` is 1 and rendering is broken. This led me to speculate that in the latter case, the `element[0].innerHTML = text` line replaced elements that were still in the MathJax queue, waiting to be rendered. The newly created elements are not in the queue, and so the rendering never happens. I've "fixed" this issue by editing `IPython/html/static/notebook/js/textcell.js`, and changing 
```{javascript}
that.events.trigger("rendered.MarkdownCell", {cell: that});
```
to
```{javascript}
var f = function(cell){cell.events.trigger("rendered.MarkdownCell", {cell: cell});};
MathJax.Hub.Queue([f, that]);
```
which delays the trigger until the MathJax rendering is complete. This does fix the issue, but I don't know if this is a very good way of doing so. It might be preferable to do this waiting on the python-markdown side.

**Comment by juhasch** [comment]
Hi, thanks for reporting this. I don't see this behavior at all, so it is difficult for me to understand what is going on exactly. For me `MathJax.Hub.queue.pending` is alway 1 when `endered.MarkdownCell` is triggered and everything works fine.

Can you give more information about your system and IPython version ?
A not working notebook would be very helpful, too.

**Comment by maximerischard** [comment]
I haven't had this issue for a while, without the above fix.
