### ISSUE TITLE
.ipython should read .jupyter?

### ISSUE THREAD

**Issue by josephcslater** [ipython-contrib/IPython-notebook-extensions#266]
I know the transition to Jupypter is causing things to be in heavy flux and a challenge to keep on top of. However, it seems to me that .ipython in the wiki should read .jupyter in the "config" wiki. However, i haven't gotten it to work, so I'm not sure.

**Comment by jcb91** [comment]
Hi there.

Yes, I'm afraid it's confusing with all the changes from 3.x to 4.x, it took me a while to figure it all out.
I've edited the wiki page to reflect the current truth as far as I understand it from my working installation - let me know if it helps (or doesn't!).

Best of luck!

Josh

P.S, if you're interested in where general extension and config things live now, there's a fairly nice summary at [wiki/Home_Jupyter](https://github.com/ipython-contrib/IPython-notebook-extensions/wiki/Home_Jupyter).

**Comment by josephcslater** [comment]
Thanks! I'll let you know how this newbie copes when I get back to trying it. (Life as a figurative fireman right now). I certainly didn't pick the easiest time to start learning Python and IPython, but it's been exciting, for sure!

**Comment by jcb91** [comment]
No worries, hopefully the fires are under control ^_^

This really is moving fast, though:

The 4.x (master) branch of the repository has now been re-organized by @juhasch to have a much simpler installation procedure, which you can read about in [the readme](https://github.com/ipython-contrib/IPython-notebook-extensions/blob/master/README.md). That's your best bet for now, I think. As before, please let us know whether this approach does/doesn't work once you get a chance to try.

J

**Comment by juhasch** [comment]
If you have problems with the extensions, simply open another issue.
