### ISSUE TITLE
YAML file format

### ISSUE THREAD

**Issue by josephcslater** [ipython-contrib/IPython-notebook-extensions#267]
Is this supposed to be a file of a specific name? It's not clear what one should do with this. What to put in it is made explicit, but what to name it isn't.

**Comment by juhasch** [comment]
The file can have an arbitrary name, as long as it has the extension `yaml`.
I have added this information to [config extension](https://github.com/ipython-contrib/IPython-notebook-extensions/wiki/config-extension) in the Wiki.
