### ISSUE TITLE
Chrome clipboard doubles cells when pasting

### ISSUE THREAD

**Issue by jcb91** [ipython-contrib/IPython-notebook-extensions#285]
As commented by @Babber on #277, you can see this by:

> Create a new notebook, with the single cell:
> 
> ```javascript
> %%javascript
> require(['base/js/utils'],
> function(utils) {
> utils.load_extensions('usability/chrome-clipboard/main');
> });
> ```
> Execute it, then select it, then hit Ctrl-V twice. The second will insert the cell twice, thus resulting in four > copies of the cell in total, instead of three.
> I don't know yet how to reproduce the other bug when it inserts the cell inside an other one, but that happened many times too.

**Comment by juhasch** [comment]
It looks like every time you paste the cell, the extension gets loaded again. The solution would be to prevent loading an extension multiple times.

**Comment by jcb91** [comment]
I don't think it's quite that simple...
I don't have have the extension activated (and it doesn't appear in my nbconfig/notebook.json), yet it (the extension) gets loaded when I open the notebook containing the cell.

**Comment by juhasch** [comment]
If you add a flag in global namespace to prevent loading multiple times, the problem goes away.
Just add 
```
var chrome_clipboard_loaded = chrome_clipboard_loaded || false;
```
and
```
if (window.chrome_clipboard_loaded === true) return function() {};
window.chrome_clipboard_loaded = true;
```
in the `load_ipython_extension` function.

BTW. I have just merged the reorganization PR. The repo now looks different.Unfortunately I have lost the history, not sure how to get it back.

**Comment by jcb91** [comment]
Although preventing loading twice does make it go away, I think it points at a deeper problem with the notebook rather than the extension, since
* the use of requirejs ought to prevent a module being loaded twice anyway
* somehow javascript which once came from the notebook's contents is being executed on page load, which looks like quite a security flaw to me
Anyway, it seems not to be something to fix in the extension.

I'm not really sure what you mean about the lost history - what history have you lost?

J

**Comment by juhasch** [comment]
Actually I think only the `load_ipython_extension` function inside the notebook extension is called many times. So the solution is probably not to register the event handlers there, but in the body of the extensions that is loaded only once.

Regarding history: I have moved some files and so the link to the git commit history at the old location was lost. Now it is hard to look at the old commits and the authors of the commits.

**Comment by jcb91** [comment]
Ah, I see what you mean, `require` only loads the extension once, but `utils` will happily execute the `load_ipython_extension` function multiple times, right?

Well, that puts my mind at rest for the first point I raised above. However, I don't think it's a good idea to register handlers in the definition of the extension, even if it doesn't later get loaded. It's a paradigm that's liable to get people into unintended and unforeseen consequences later on. Equally, expecting every extension to check whether or not it's already been loaded will result in a lot of duplication, and potential for errors when extensions don't manage it correctly. Perhaps a better method would be for `utils` to just keep track of which extensions it's already called `load_ipython_extension` for, in a similar way to require keeping track of what objects it's fetched. It would equally be possible to add the potential to force calling `load_ipython_extension` again in order to reload a given extension if it's really desired, although I can't immediately think of a use for that.

The second point I raised is unrelated to extensions, and is related instead to trusted/untrusted notebooks, in that the javascript cell *is* executed on loading a *trusted* notebook, and this is the intended behaviour. I was worried because I hadn't realized I was using a trusted notebook, so didn't think it should work.

As for history, I don't know, all the links seem to work ok for me, although of course the files they talk about changing may have moved, which can complicate things rather!

**Comment by juhasch** [comment]
I certainly did not expect `locad_ipython_extension` to be called multiple times, so yes I think it would be a good idea to keep track of the extensions that are already loaded in the notebook code itself.
I don't think calling `load_ipython_extension` is intentional,  so I would say it is a bug.

Having a list of currently loaded extensions would also be nice for users to see.

**Comment by juhasch** [comment]
Would you open an issue for this at jupiter/notebook ?

**Comment by jcb91** [comment]
sure, will do
