### ISSUE TITLE
python-markdown messes up custom setting of the mathjax hub

### ISSUE THREAD

**Issue by wllmtrng** [ipython-contrib/IPython-notebook-extensions#299]
The following issue was discovered using ipython 4.0.0 and the latest commit on the master branch for Ipython-notebook-extensions

For my particular case, the enabling of the python-markdown feature forces the alignment of mathJax  "$$" calls to be center aligned, even when MathJax is reconfigured to be left aligned in javascript:

```html
%%html
<script>
    MathJax.Hub.Config({
                        TeX: {
                           extensions: ["AMSmath.js"]
                           },
                tex2jax: {
                    inlineMath: [ ['$','$'], ["\\(","\\)"] ],
                    displayMath: [ ['$$','$$'], ["\\[","\\]"] ]
                },
                displayAlign: 'left', // Change this to 'center' to center equations.
                displayIndent: "4em"
        });
</script>
```

## Here is a sample test case:
<img width="1133" alt="screen shot 2015-09-13 at 11 32 59 am" src="https://cloud.githubusercontent.com/assets/1335855/9838189/90ea9066-5a0b-11e5-8520-695a9686403c.png">

## With python markdown disabled, the MathJax will correctly display left aligned with 4em indent:
<img width="1129" alt="screen shot 2015-09-13 at 11 33 53 am" src="https://cloud.githubusercontent.com/assets/1335855/9838193/ac0b4818-5a0b-11e5-8cc0-1a6d8623ddb8.png">

## With python markdown enabled, the MathJax will incorrectly be displayed as center aligned:
<img width="903" alt="screen shot 2015-09-13 at 11 42 15 am" src="https://cloud.githubusercontent.com/assets/1335855/9838218/8d123736-5a0c-11e5-8ef9-35b9631a878f.png">

**Comment by juhasch** [comment]
I see this too, however also without the Python markdown extension. 
I fear that it is not possible to reliably configure MathJax this way. As I understand, there is no good way to configure MathJax in the notebook at all, but would love to be shown otherwise.

**Comment by wllmtrng** [comment]
Are you able to reproduce it without python-markdown in a reliable manner? I am unable to. I can submit a bug in the ipython repo if it's possible to show.

**Comment by juhasch** [comment]
MathJax rendering is a little tricky. I found something that causes the behavior you see.
The extension changes the html contents even if not necessary and does not call MathJax to render it.
Should be fixed now.

Still don't know why only sometimes the MathJax configuration seems to work.
