### ISSUE TITLE
Controlling the precision in the markdown extension

### ISSUE THREAD

**Issue by lhcamilo** [ipython-contrib/IPython-notebook-extensions#300]
First of all, thank for all your hard work with the extensions. You guys have been making jupyter a force to be reckoned with. Though  there is one thing that I would like to ask if there is any way to control the precision of the markdown output? 

If not, then I reckon this would be  a feature request.  I will study the code a bit but at the moment it is a bit too advanced for myself

Thanks in advance.

**Comment by juhasch** [comment]
You can try the IPython magic `%precision 2` if you only want to see two numbers after the digit.
Or you can use Python formatting like `{{ '%.2f' % (1/3)}}` or the Pythonic way `'{0:.2f}'.format(1/3)`

**Comment by lhcamilo** [comment]
That did it. I didn't realize that string formatting was applicable here. 

Thanks
