### ISSUE TITLE
I made some wiki updates which could be merged

### ISSUE THREAD

**Issue by jcb91** [ipython-contrib/IPython-notebook-extensions#307]
The addition/deletion of the wiki-images directory got me thinking.

Since I can't push to the wiki repository, or submit pull requests, I've followed the procedure suggested at http://stackoverflow.com/questions/10642928/how-to-pull-request-a-wiki-page-on-github.  Essentially, clone the wiki to a new github repository (in this case https://github.com/jcb91/IPython-notebook-extensions-wiki, which also has itself as its own wiki, so you can see the changes live) and make changes to that, which you can review and incorporate/discard as you see fit. I think it should be an improvement though, hopefully. My updated version stores wiki images as part of the wiki repo, so we can do away with the wiki-images directory in the main repo if desired

J

**Comment by juhasch** [comment]
Done. Thanks.
