### ISSUE TITLE
nbextensions.html not found. 

### ISSUE THREAD

**Issue by josephcslater** [ipython-contrib/IPython-notebook-extensions#313]
I'm taking a swing at getting things installed again. Looks like it should have been fairly easy. 4 hours later, my head is swimming. 

python notebook runs but fails to load the extensions, apparently because of this line pulled out of the log:
``jinja2.exceptions.TemplateNotFound: nbextensions.html``

- My process was to check out the latest trunk, then ``python setup.py install``, nothing fancy. 
- I have python/jupyter installed via macports on El Capitan. Had already activated three extensions via ``jupyter-nbextension-3.4 ``
- The log shows them being recognized, but they certainly aren't functional, perhaps because of this missing file?

Further: ``http://localhost:8998/nbextensions`` isn't working either. 

This should likely be listed as two bugs, but as I have two failures and one piece of "cause", I don't know what is what for a second issue report. 

#### Full log at startup

``jslater> ipython notebook
/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/IPython/utils/path.py:258: UserWarning: get_ipython_dir has moved to the IPython.paths module
  warn("get_ipython_dir has moved to the IPython.paths module")
[I 13:38:12.393 NotebookApp] Serving notebooks from local directory: /Users/jslater/Documents/CourseMaterial/ME7160/Notes
[I 13:38:12.393 NotebookApp] 0 active kernels 
[I 13:38:12.393 NotebookApp] The IPython Notebook is running at: http://localhost:8998/
[I 13:38:12.393 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[24125:1295:0924/133819:ERROR:display_info_provider_mac.cc(30)] Not implemented reached in virtual void extensions::DisplayInfoProviderMac::UpdateDisplayUnitInfoForPlatform(const gfx::Display &, extensions::core_api::system_display::DisplayUnitInfo *)
[W 13:38:27.226 NotebookApp] 404 GET /nbextensions/hide_input.js?v=20150924133812 (::1) 15.65ms referer=http://localhost:8998/notebooks/Chapter_2.ipynb
[W 13:38:27.248 NotebookApp] 404 GET /nbextensions/codefolding.js?v=20150924133812 (::1) 2.89ms referer=http://localhost:8998/notebooks/Chapter_2.ipynb
[W 13:38:27.301 NotebookApp] 404 GET /nbextensions/dragdrop.js?v=20150924133812 (::1) 21.56ms referer=http://localhost:8998/notebooks/Chapter_2.ipynb
[I 13:38:31.380 NotebookApp] Kernel started: 712f09f6-6ef7-445b-8f34-a7398525772a
[W 13:38:33.873 NotebookApp] 404 GET /static/components/MathJax/jax/element/mml/optable/BasicLatin.js?rev=2.5.3 (::1) 3.03ms referer=http://localhost:8998/notebooks/Chapter_2.ipynb
[I 13:39:16.229 NotebookApp] Found 4.x extension NbExtensions menu item
[I 13:39:16.239 NotebookApp] Found 4.x extension Printview
[I 13:39:16.246 NotebookApp] Found 4.x extension zenmode
[I 13:39:16.250 NotebookApp] Found 4.x extension Chrome Clipboard
[I 13:39:16.254 NotebookApp] Found 4.x extension Codefolding
[I 13:39:16.258 NotebookApp] Found 4.x extension Drag and Drop
[I 13:39:16.262 NotebookApp] Found 4.x extension ExecuteTime
[I 13:39:16.265 NotebookApp] Found 3.x extension Exercise
[I 13:39:16.268 NotebookApp] Found 3.x, Jupyter (4.x) extension (some) LaTeX environments for Jupyter
[I 13:39:16.276 NotebookApp] Found 4.x extension Limit Output
[I 13:39:16.279 NotebookApp] Found 4.x extension Navigation-Hotkeys
[I 13:39:16.283 NotebookApp] Found 4.x extension Python Markdown
[I 13:39:16.286 NotebookApp] Found 4.x extension Rubberband
[I 13:39:16.294 NotebookApp] Found 4.x extension Ruler
[I 13:39:16.298 NotebookApp] Found 4.x extension Runtools
[I 13:39:16.301 NotebookApp] Found 4.x extension Search-Replace
[I 13:39:16.304 NotebookApp] Found 4.x extension Skip-Traceback
[I 13:39:16.311 NotebookApp] Found 3.x 4.x extension Toggle all line numbers
[E 13:39:16.311 NotebookApp] Uncaught exception GET /nbextensions (::1)
    HTTPServerRequest(protocol='http', host='localhost:8998', method='GET', uri='/nbextensions', version='HTTP/1.1', remote_ip='::1', headers={'Host': 'localhost:8998', 'Upgrade-Insecure-Requests': '1', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.99 Safari/537.36', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', 'Accept-Encoding': 'gzip, deflate, sdch', 'Accept-Language': 'en-US,en;q=0.8', 'Connection': 'keep-alive'})
    Traceback (most recent call last):
      File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/tornado/web.py", line 1413, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/tornado/web.py", line 2721, in wrapper
        return method(self, *args, **kwargs)
      File "/Users/jslater/Library/Jupyter/extensions/nbextensions.py", line 85, in get
        page_title="Notebook Extension Configuration"
      File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/notebook/base/handlers.py", line 249, in render_template
        template = self.get_template(name)
      File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/notebook/base/handlers.py", line 245, in get_template
        return self.settings['jinja2_env'].get_template(name)
      File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/jinja2/environment.py", line 812, in get_template
        return self._load_template(name, self.make_globals(globals))
      File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/jinja2/environment.py", line 774, in _load_template
        cache_key = self.loader.get_source(self, name)[1]
      File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/jinja2/loaders.py", line 187, in get_source
        raise TemplateNotFound(template)
    jinja2.exceptions.TemplateNotFound: nbextensions.html
[E 13:39:16.323 NotebookApp] {
      "Host": "localhost:8998",
      "Upgrade-Insecure-Requests": "1",
      "Connection": "keep-alive",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
      "Accept-Encoding": "gzip, deflate, sdch",
      "Accept-Language": "en-US,en;q=0.8",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.99 Safari/537.36"
    }
[E 13:39:16.323 NotebookApp] 500 GET /nbextensions (::1) 113.77ms referer=None
[I 13:39:22.393 NotebookApp] 302 GET / (::1) 0.69ms``

**Comment by juhasch** [comment]
It looks like you are mixing IPython 3.x with nbextensions for Jupyter/IPython 4.x.
This probably will not work. Did you check out the 3.x branch ?

**Comment by josephcslater** [comment]
I don't think that's the case by the (amateur) test that my notebooks come up with the Jupyter logo. Further, ``python --version`` gives me 4.0.0

Somehow I have spell checking working. My poor memory leads me to recall that I had it working before 4.0 and that it migrated correctly. 

What's the best way to check  to be sure? Is "showing" of the Jupyter logo enough?

**Comment by juhasch** [comment]
The notebook now starts with `jupyter notebook`. Can you try this ?

**Comment by josephcslater** [comment]
Now I have to admit being very confused, and you have every right to be quite frustrated with me. 

It's now working. Further, I can't tell you why. This happened to me before. I cannot be sure what my bouncing around finally "fixed" (although /nbextensions.html still can't be found). 

It works whether I run `ipython notebook` (which is actually ipython-3.4 resulting in jupyter) or `jupyter-notebook-3.4`. I believe the 3.4 is indicating the targeted version of python, although I'm really not 100% sure. I saw some traffic on the macports list regarding migration naming issues/strategy. I think there was an intent to leave the call as `ipython` for a bit so that users wouldn't think it had disappeared? Nevertheless, ipython-3.4 is resulting in jupyter.   

I do know that the wiki lists 2 variations of installation instructions. I suspect the expectation is they should act the same, but my experience didn't support that. 

In *General installation instructions*,
`jupyter nbextension install <name of extension>`
is the installation method. This is what I had (I believe) done. However, on macports, it's apparently intended to be a separate call (`jupyter-nbextension-3.4`). etc.

Up above, the method of *So where can I find things now?* followed by *Checking/loading notebook extension from IPython* provides notebook cells that executed and worked for me. 

It's apparent to me that earlier today I wasted time (my fault) as I didn't have the most recent distribution, and I was manually installing files per old instructions instead of simply running the `setup.py install`. The cells didn't execute favorably (yielding False) because I didn't have things installed properly, but the command line installation method did not provide a similar error (no indication of failure or success). 

So: `jinja2.exceptions.TemplateNotFound: nbextensions.html` is still happening, but installations are now working for me.

**Comment by jcb91** [comment]
Hi @josephcslater. I think at least some of the confusion is down to how macports packages things, although I think you have other problems going on too. 

Macports stuff
-------------------
As you note, macports provides `jupyter-nbextension-3.4`. As I understand it, your guess is correct, and the 3.4 denotes the python version (I also have a `jupyter-nbextension-2.7`). In other situations, macports deals with multiple python versions by installing different python versions as `python2.7`, `python3.4` etc, and then using the `port select` mechanism to create appropriate symlinks (e.g. `port select python27` results for me in a situation where the `python` on my path is a symlink to `/opt/local/bin/python2.7`. This also applies to ipython, but so far it seems that nobody's made a `select` type solution for the notebooks, so you (may) need to manually create the symlinks. I made a symlink `/opt/local/bin/jupyter -> /opt/local/bin/jupyter-2.7`. In order for the subcommands (e.g. notebook, nbextension etc) to function as well, executables named `jupyter-<subcommand>` need to exist on the path. In order to get this working, I just made another bunch of symlinks of the form `/opt/local/bin/jupyter-notebook -> /opt/local/bin/jupyter-notebook-2.7` (there are a few). Really, this should all be handled by a macports jupyter select. I don't know off the top of my head how to write one, but may get around to it at some point (or someone else may ^_^).

**Comment by jgburd79** [comment]
I have WinPython-64bit-3.4.3.6 installed and I have Jupyter (4x) notebook installed and running. I've was able to install the nbextensions and it shows up in the  ~\settings\nbextensions. I cannot get it to recognize the extensions and the nbextensions.html does not show up. it is just a blank page.

**Comment by juhasch** [comment]
Closing as outdated.
