### ISSUE TITLE
Conda build instructions in readme not working

### ISSUE THREAD

**Issue by schoolie** [ipython-contrib/IPython-notebook-extensions#345]
In order to build and install on Windows 64, python 2.7, conda 3.18.1, I had to add  --use-local to the conda install command.

Didn't work:
conda install nbextensions

Worked:
conda install --use-local nbextensions

**Comment by nehalecky** [comment]
+1, seriously lost an hour with this (I'm slow).

Seems I'm not the only one, as per https://github.com/jupyter/notebook/issues/389. 

@schoolie, I don't think it's a platform specific issue, as I'm running an ubuntu vm—my conda info:
```bash
$ conda info
Current conda install:

             platform : linux-64
        conda version : 3.18.3
  conda-build version : 1.18.1
       python version : 2.7.10.final.0
     requests version : 2.8.1
     root environment : /home/vagrant/miniconda-3.16.0  (writable)
  default environment : /home/vagrant/miniconda-3.16.0/envs/analytics
     envs directories : /home/vagrant/miniconda-3.16.0/envs
        package cache : /home/vagrant/miniconda-3.16.0/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : /home/vagrant/.condarc
    is foreign system : False
```
I will try and submit a pull request, but the install instructions should be a sequence of commands that includes everything to get up and running. I think the following would work for a majority of cases:

```bash
$ source activate root  #activate root conda env
$ conda install anaconda-client conda-build
$ git clone https://github.com/ipython-contrib/IPython-notebook-extensions.git
$ conda build IPython-notebook-extensions
$ source activate <target-env>  #switch back to target conda env
$ conda install --use-local nbextensions
```
and finally, navigate to the running Jupyter instance nbextensions page, by default at:
https://127.0.0.1:8888/nbextensions

Good luck! :)

**Comment by juhasch** [comment]
Thanks for the example!

**Comment by janschulz** [comment]
IMO this can be closed as we currently do not have conda instructions.

**Comment by jcb91** [comment]
Yep, this is fixed (in the sense that we don't mention conda) by #500

**Comment by jcb91** [comment]
although, they do still appear on the wiki, I think...
