### ISSUE TITLE
Printview does not treat special characters as ' ' and '('

### ISSUE THREAD

**Issue by wsfreund** [ipython-contrib/IPython-notebook-extensions#358]
I've just installed IPython4.0 and the notebook (jupyther) extensions. I've enabled the plugin printview and when I clicked on it, it would give the following error:

```
[I 21:08:37.989 NotebookApp] Saving file at /Creating and configuring CERN VM (for ATLAS).ipynb
sh: -c: line 0: syntax error near unexpected token `('
sh: -c: line 0: `jupyter nbconvert —to html Creating and configuring CERN VM (for ATLAS).ipynb'
```

Then I removed the parenthesis and it would give error considering that the spaces would represent each one a different input for the command. Thus, I changed the spaces for _ and it worked.

I couldn't find it reported before, sorry if this is already known.

**Comment by jcb91** [comment]
Ah yes, this is a bug. In fact, it's potentially a pretty serious security flaw, since the filename is passed to OS unescaped. I'll look for ways to fix it.

**Comment by jcb91** [comment]
@wsfreund I've made an attempt at a fix. Please let me know whether this works for you, when you get a chance

**Comment by wsfreund** [comment]
It works for both cases. Thanks!
