### ISSUE TITLE
Drag-and-drop plugin not working for Jupyter on Mac OS X 10.10

### ISSUE THREAD

**Issue by dmyersturnbull** [ipython-contrib/IPython-notebook-extensions#362]
Steps to reproduce:

1. Install Jupyter from Anaconda and open a new notebook with either Python 2 (2.7.10) or Python 3 (3.4.3) kernel.
2. Install the drag-and-drop extension from a fresh checkout of IPython-notebook-extensions:
```
jupyter nbextension install usability/dragdrop
jupyter nbextension enable usability/dragdrop
```

3. Confirm that the plugin is enabled using `cm.get('notebook')`.

4. Drag and drop an image from Finder.

Result: Text representation of binary is displayed rather than image.

**Comment by dmyersturnbull** [comment]
Left out: Nothing shown in Javascript console.

**Comment by juhasch** [comment]
Can you say
* what Browser you use
* what type of image you used. Does this happen for different images / image types
* Is the binary output in the code input area or in the output

**Comment by dmyersturnbull** [comment]
- Chrome and Firefox
- PNG, GIF, and JPEG
- The binary output is in the code input area

**Comment by juhasch** [comment]
This means that the contents of the image is handled by code mirror (the text editing component).
So my guess would be the extensions is not really active.
Which version of the IPython/Jupyter notebook are you using ?
Does the Javascript console show:
`Loaded extension: usability/dragdrop/main`

**Comment by dmyersturnbull** [comment]
`jupyter --version` shows 4.0.4.

When I load a notebook, the Javascript console shows (I didn't see/notice this before):
```
http://localhost:8813/nbextensions/usability/dragdrop.js Failed to load resource: the server responded with a status of 404 (Not Found)
```

**Comment by juhasch** [comment]
The extension should be found at `nbextensions/usability/dragdrop/main.js`, so the notebook is trying to load the extension at the wrong place. If you disable the current one and enable the extension with the correct path it should work.

The easiest way is to install all extensions using `python setup.py install`, and then activate/deactivate the extension at the `nbextensions` web page.

**Comment by dmyersturnbull** [comment]
Okay, I ran `python setup.py install`, and it looks like the extensions were installed to `~/.jupyter`. However, `http://localhost:8939/nbextensions` returns a 404.

**Comment by juhasch** [comment]
When trying to load the `nbextensions` page, do you see error messages or messages like this in the shell where you started the notebook server:
```
[I 19:28:45.525 NotebookApp] Found 4.x extension NbExtensions menu item
[I 19:28:45.528 NotebookApp] Found 4.x extension Printview
...
```

**Comment by dmyersturnbull** [comment]
I think I know what's going on. How can I delete all extensions? Where is the list of installed extensions maintained?

**Comment by juhasch** [comment]
The extensions are located in `~/Library/Jupyter/nbextensions`

**Comment by dmyersturnbull** [comment]
Thanks. The drop-down extension and nbextensions page both work now, so this isn't a bug.

I was running Jupyter at /usr/local/bin/jupyter (4.0.4). I'm not sure where that came from, since to my knowledge I only installed from Anaconda. However, the copy under ~/anaconda/bin/jupyter (4.0.0) works fine.
