### ISSUE TITLE
init_cell not adding button? (jupyter 4.0)

### ISSUE THREAD

**Issue by gabyx** [ipython-contrib/IPython-notebook-extensions#364]
the command :+1: 

``$([IPython.events]).on('notebook_loaded.Notebook',add_run_init_button);``

is not working correctly (?)

when I change it to simply execute the command,

add_run_init_button();

then the button is added and it works!

**Comment by jcb91** [comment]
@gabyx which extension is this in?

**Comment by gabyx** [comment]
cool thanks!

**Comment by jcb91** [comment]
ok, so I've made fix on my clone (jcb91/IPython-notebook-extensions), which is submitted as PR #367. Should hopefully fix this.

**Comment by juhasch** [comment]
Fixed by jcb91 in PR #367
