### ISSUE TITLE
chrome clipboard disables 'paste' in ipywidgets

### ISSUE THREAD

**Issue by JanSchulz** [ipython-contrib/IPython-notebook-extensions#366]
When I enable `Chrome Clipboard` and try to use a widgets, I can't c&p something into the resulting text input boxes:

```
from IPython.html.widgets import interact_manual, fixed, interact
def table_from_processed(name="", aid="", uni="", eid=False):
    print("%s | %s | %s | %s" % (name, aid, uni, eid))
_x = interact_manual(table_from_processed)
```

-> try to paste something into one of the input fields with and without the chrome clipboard extension enabled...

**Comment by juhasch** [comment]
True. Should be fixed by #372
