### ISSUE TITLE
Is there a way to limit the number of notebooks running in a single jupyter server?

### ISSUE THREAD

**Issue by jerrylam** [ipython-contrib/IPython-notebook-extensions#373]
I want to avoid users from opening too many notebooks, is this possible? Thanks.

**Comment by jcb91** [comment]
Hi @jerrylam, apologies for the delay replying. I'm not sure whether it's possible to limit the number of kernels started. Why would you want to do this? If it's from a resource-usage perspective, then bear in mind that even a single kernel is able to use a lot of resources, and has basic access to the file system, so to some extent you must trust the users you allow to use your server.

If it is possible to limit the number of kernels, this would be done by the jupyter backend, so you'd be more likely to find an answer at the main [jupyter/notebook repo](https://github.com/jupyter/notebook) than this one, which deals only with javascript extensions to the notebook frontend.

**Comment by juhasch** [comment]
Closing as out of scope for nbextensions
