### ISSUE TITLE
Search&Replace and Table of Content extension occupy the same place

### ISSUE THREAD

**Issue by janschulz** [ipython-contrib/IPython-notebook-extensions#375]
See this screenshot:
![2015-10-19_165228](https://cloud.githubusercontent.com/assets/890156/10581218/d61f9afe-7681-11e5-9757-90bdc30e19bb.png)

Not sure how to handle this, what should go where... On the other hand, S&R seems to get included in notebook proper (https://github.com/jupyter/notebook/pull/285 and https://github.com/jupyter/notebook/issues/558), so the extension can probably be dropped after the next notebook release...

**Comment by juhasch** [comment]
We could save the position of the searchbar, so it stays there when moved.
But I  guess you are right, if the new builtin functionality works we can remove the extension.

**Comment by janschulz** [comment]
This can probably be removed as the s&r functionality is obsolete with the new UI in the notebook
