### ISSUE TITLE
TOC: section tile with formatting

### ISSUE THREAD

**Issue by tritemio** [ipython-contrib/IPython-notebook-extensions#380]
When a section title has some code formatting the tile is truncated.

for example a markdown cell containing

```
# Group `photon_data`
```

will result in a TOC showing only "Group"

**Comment by JanSchulz** [comment]
We remove children here:

```
  var make_link = function (h) {
    var a = $("<a/>");
    a.attr("href", '#' + h.attr('id'));
    // get the text *excluding* the link text, whatever it may be
    var hclone = h.clone();
    hclone.children().remove(); // <- here...
    a.text(hclone.text());
    return a;
  };
```

I've no clue why this in the code (is there an anchor?). @tritemio Could you try that in your local installation if that works as you want it?

**Comment by jfbercher** [comment]
It seems that an anchor is automatically build from titles and inserted. The .remove() removes this anchor (an the linked text which is a carriage return). But so doing removes all children, including all html formatting. In my attempts 
`hclone.children().last().remove();`
which only removes the last child seems to work. Can you check from your side?

**Comment by JanSchulz** [comment]
What you propose works for me. Want to do a PR?

**Comment by JanSchulz** [comment]
@jfbercher nevermind, thought you were the original poster... PR incoming... :-)

**Comment by jfbercher** [comment]
No problem.
