### ISSUE TITLE
python-markdown does not render

### ISSUE THREAD

**Issue by bodokaiser** [ipython-contrib/IPython-notebook-extensions#381]
Hey,

I just followed the wiki guide to install some nbextensions:

1. clone the `master` branch of this repo and use `setup.py`
2. use `jupyter nbextensions enable <name>`
3. use following configuration in `~/.ipython/profile_default/ipython_config.py`

```python
c = get_config()

c.InteractiveShellApp.matplotlib = "inline"

c.NotebookApp.server_extensions = ['nbextensions']

c.Exporter.template_path = [os.path.join(jupyter_data_dir(), 'templates')]
c.Exporter.preprocessors = [
            "pre_codefolding.CodeFoldingPreprocessor",
                "pre_pymarkdown.PyMarkdownPreprocessor"
                ]

c.NbConvertApp.postprocessor_class = "post_embedhtml.EmbedPostProcessor"
```

The result is that for example the code folding extension works as should. Unfortunately I do not get the python markdown extension running (e.g. `{{ expr }}` stays unchanged). I also defined my notebook as trusted however nothing changes.

What could be the problem?

**Comment by juhasch** [comment]
I can't see from what you have written, if the extension is enabled.
Can you look at the Javascript console output in your browser if you see this line.
`Loaded extension: usability/python-markdown/main` ?

**Comment by bodokaiser** [comment]
Ah yes, I see there are `404`s `http://localhost:8888/nbextensions/usability/python-markdown.js`.

How do I fix this?

**Comment by juhasch** [comment]
The easiest way is to install all extensions using `python setup.py install`, start the jupyter notebook and then go to `http://localhost:8888/nbextensions` where you should see this:
![](https://github.com/ipython-contrib/IPython-notebook-extensions/raw/master/nbextensions/config/icon.png)

Now you can activate/deactivate all available extensions. Using `jupyter nbextensions enable <name>` leads to the difficulties you encountered, i.e. you specify an extension name that is not the name of the actual file.

**Comment by bodokaiser** [comment]
I found some errors in my config. Now I can see the interface at `http://localhost:8888/nbextensions`. I checked and found that `python-markdown` is enabled but still the chrome console gives a `404` on `http://localhost:8888/nbextensions/usability/python-markdown.js`. I checked the `nbextensions` folder and found that there only is a `nbextensions/usability/python-markdown/main.js` could this be a naming issue?

**Comment by juhasch** [comment]
Yes. Unfortunately an extension name can either be a subdirectory or the actual extension minus .js .
You need to manually disable the extension using `jupyter disable python-markdown` or clean up the json config file manually.

**Comment by bodokaiser** [comment]
I guess I will finde the solution here: https://github.com/ipython-contrib/IPython-notebook-extensions/issues/282 Thank you for your help!

**Comment by kostrykin** [comment]
@bodokaiser So how did you actually solve this? To me it is not clear from the referenced issue.

**Comment by bodokaiser** [comment]
@kostrykin Sorry this has been too long ago. I guess api changed since 2015 too.

**Comment by jcb91** [comment]
@kostrykin, please open a new issue if you're having problems, it's probably best to keep a separate thread from this older one :)
