### ISSUE TITLE
Full-service Latex/PDF output

### ISSUE THREAD

**Issue by bbirand** [ipython-contrib/IPython-notebook-extensions#399]
I really like the idea of exporting IPython notebooks as PDF reports that I can send around. `nbconvert` makes this extremely simple, but for my uses cases, only goes 90% of the way. 

I created two pull requests that made things more useful for me:

* The metadata added by `hide_input_all` didn't seem to be correct. They were not being parsed in the Latex template. This is my attempt at fixing this #397 
* The `printviewlatex` template was only checking cell-level `hide_input` metadata. I added checks for the notebook-level ones in #398 

So at this point, if I activate "hide all input cells", and then "Export as PDF", I get a reasonably good output. 

But I need advice for some other points:

* I mainly use the output for displaying plots. But the matplotlib `repr` string is also displayed above every figure. For subplots, I get an array of figures, which looks even uglier. If there was a way of keeping only the figure, and nothing, else this would help a lot. Any idea how I could go about implementing this? There is a filter that converts the cells' content to Latex, so maybe there?

* Sometimes one may want to include a computed result in the report itself. A cool way of doing this would be to have a function (or class), that keeps only the argument. So kind of like `print` or IPython's `display`. Maybe can also have some arguments about 

* Ultimately, I'd like to have an extension that always does the following, regardless of the notebook-level metadata.

I think most of these points are fairly straightforward, and I can get them done with some thoughts..

Thanks!

**Comment by juhasch** [comment]
Thanks you. I have merged one PR, I am not sure about the other (i.e. the True/False assignment should be the same as in the cell level extension and not require an explicit string).

For you questions:
* You should be able to suppress the repr string by adding a semicolon at the end of the last line in the cell.
* Regarding your second question, what are you missing with the print/display function ?
If you want to have results printed in a markdown cell, you can try the Python markdown extension.
* Finally, if you always want to hide input cells, simply modifying the tplx template to not test the metadata should be enough ?

**Comment by bbirand** [comment]
Hi @juhasch , Thanks for the input. I think your post actually answers most of my questions. I created a new template that always hides the input cells. Up to you, but maybe it might make sense to have a single extension that directly does this, so that my not-so-tech-savvy colleagues can get going right away.

I'll check out Python markdown, sounds incredibly interesting!
