### ISSUE TITLE
Add minrk's writeandexecute extension?

### ISSUE THREAD

**Issue by bbirand** [ipython-contrib/IPython-notebook-extensions#406]
Would it be of interest to include this extension to this repo?

https://github.com/minrk/ipython_extensions/blob/master/extensions/writeandexecute.py

It looks pretty interesting, especially for sharing code across notebooks..

**Comment by JanSchulz** [comment]
This repo is just for notebook extensions, but there is a repo for ipython extension at https://github.com/ipython-contrib/IPython-extensions. The writeandexecute extension is already included: http://ipython-extensions.readthedocs.org/en/latest/magics.html#cellmagic-writeandexecute
