### ISSUE TITLE
Patch to make printview work with slides

### ISSUE THREAD

**Issue by petrushy** [ipython-contrib/IPython-notebook-extensions#410]
To make printview open the right url for slides:

    --- main.js.old Thu Nov 12 17:56:09 2015
    +++ main.js     Fri Nov 13 07:35:13 2015
    @@ -22,6 +22,8 @@
         if (config.data.hasOwnProperty('printview_nbconvert_options') ) {
             nbconvert_options = config.data.printview_nbconvert_options;
             if (nbconvert_options.search('pdf') > 0) extension = '.pdf';
    +            if (nbconvert_options.search('slides') > 0) extension = '.slides.html';
    +
         }
         if (config.data.hasOwnProperty('printview_open_tab') ) {
             if (typeof(config.data.printview_open_tab) === "boolean") {

**Comment by juhasch** [comment]
Sounds good. See #413.
