### ISSUE TITLE
Folder ReOrg: Consider making each backend extension (in extensions folders) as seperate packages?

### ISSUE THREAD

**Issue by haobibo** [ipython-contrib/IPython-notebook-extensions#421]
Currently, each backend extension (e.g.:ipy-aspell-server.py) are all put into the `extensions` folder.

Shall we consider make the backend extension into python packages? Because some backend extensions can be complicated with many classes and functions.
It will be a better practice to put each module into a folder and make it as package (entrance file as `__init__.py`).

Besides, template files are currently in a different folder (`templates`). I think we can also put template files of each backend extension into the same folder with correspondent `__init__.py` files. Because template files are coupled with handlers.

So that files of each extension can all be put into one folder (actually static files like js or css can also be put in same folder) instead of three folders (`extension`, `nbextensions`, `templates`), which makes each extension package more independent.

**Comment by hiaselhans** [comment]
:sunflower: 
I hope for something like this so there could be an easy way to provide extensions installable via pip..
the extension loader could also look at a certain package-entry-point (ipython.contrib.extensions or so) which would make installation via pip pretty straight...

**Comment by juhasch** [comment]
You might want to take a look here for some ideas:
https://github.com/ipython-contrib/IPython-notebook-extensions/issues/393

Sorry, nothing ready yet.

**Comment by damianavila** [comment]
Inside Continuum we are thinking and working in some ways to install extensions in an easy way, you should probably hear some new in some weeks... I will ping here when we have something consistent and useful...

**Comment by haobibo** [comment]
@damianavila  Since project Jupyter Notebook has introduced a new mechanism to install and manage `nbextension` and `serverextension` (see PR: https://github.com/jupyter/notebook/pull/879), do you think this project should have a big migration to accustom that change?

**Comment by damianavila** [comment]
@haobibo yes... probably... we should open an issue for this (if it is not already opened).

**Comment by jcb91** [comment]
If everything becomes a separate package, would we be better of splitting to separate repos, or make them all part of a single pip-package?

**Comment by haobibo** [comment]
@jcb91 I would vote for separate packages, but they still can be hosted on this single GitHub repo.

**Comment by jcb91** [comment]
Makes sense. I've also been thinking about this for a while, as mentioned in #577, which is pretty much a vote for doing this, with a query on names.

Templates are slightly more complicated to incorporate (see https://github.com/jupyter/notebook/issues/1339), but only slightly. The majority of our templates are for nbconvert exporters/importers, anyway.

**Comment by jcb91** [comment]
Although, on closer inspection, there are only two actual server extensions, `nbextensions.py` and `ipy-aspell-server.py`. The latter of the two exists to support an nbextenion which hasn't been updated for 4.x, and its use is discouraged on its wiki page (see https://github.com/ipython-contrib/IPython-notebook-extensions/wiki/Aspell) in favour of pure-javascript checkers, due to the reduced security headaches involved. Since we now have a pure-js aspell-based spellchecker as part of _this_ repo, I think we might be safer to dispense with aspell server extension.
