### ISSUE TITLE
Fix codefolding so that cells in already created notebooks work

### ISSUE THREAD

**Issue by ahhsia** [ipython-contrib/IPython-notebook-extensions#422]
I can get codefolding to work on newly created notebooks after I activate it. 
I can't get it to even show the gutter with code-folding arrow on existing notebooks . 

I get a Javascript error in foldcode.js on existing notebooks that doesn't occur on newly created ones. 
TypeError: funcs[i] is not a function
```var found = funcs[i](cm, start);```
on line 112 of  foldcode.js
```
  CodeMirror.registerHelper("fold", "combine", function() {
    var funcs = Array.prototype.slice.call(arguments, 0);
    return function(cm, start) {
      for (var i = 0; i < funcs.length; ++i) {
        var found = funcs[i](cm, start);
        if (found) return found;
      }
    };
  });
```
Missing metadata on already created cells/notebooks?

**Comment by ahhsia** [comment]
Hmm. Actually, the folds go away when I close the notebook and reopen it. Even the newly created ones that were working.

**Comment by ahhsia** [comment]
I increased the timeout in main.js for the initGutter call in line 198
from
    setTimeout(initGutter, 100)
to 
    setTimeout(initGutter, 1000)
and it seems to be working on my admittedly simple test notebooks right now.

**Comment by juhasch** [comment]
There is a race condition somewhere when loading the codefolding extensions. I can currently not investigate this, so good if your fix helps you for the time being.

**Comment by halflings** [comment]
Can someone look into this?

After having code folding working for quite some time, I opened my notebook one day and found that the code folding extension wouldn't work anymore... (which is problematic because I rely on it to hide some very large portions of code).

**Comment by jcb91** [comment]
I can take a look, if you could provide an example notebook that will trigger the problematic behaviour

**Comment by halflings** [comment]
All notebooks do not work in my case (for now anyway; I remember it worked again at one point, unsure what triggers that). I tried disabling and enabling the extension but that didn't fix it.
You can test with the notebook attached. (just a comment and a function; doesn't fold in my case)
![skarmavbild 2016-02-18 kl 16 27 54](https://cloud.githubusercontent.com/assets/1626936/13148219/a7b5effc-d65c-11e5-8cf8-a7db2c047bd0.png)
![skarmavbild 2016-02-18 kl 16 28 05](https://cloud.githubusercontent.com/assets/1626936/13148218/a7a0bfa6-d65c-11e5-8010-580f822ac99c.png)



[Test.ipynb.zip](https://github.com/ipython-contrib/IPython-notebook-extensions/files/136418/Test.ipynb.zip)

**Comment by jcb91** [comment]
Ok, thanks for the example. Annoyingly though, it seems to fold fine for me. This inconsistent behaviour points towards, as @juhasch suggested above, some kind of race condition. I'll leave codefolding enabled for my own work, and keep an eye out in case at some point I find it misbehaving so I can address it, but in the meantime, I'm not sure what I can do, really. If you could post any javascript console output, that might help?

**Comment by juhasch** [comment]
You could try replacing line 197 and 198 with this:
``` 
require(['./firstline-fold'], function() { setTimeout(initGutter, 100) });
```
or increase the timeout value from 100 to 1000.

**Comment by jcb91** [comment]
Yeah, my first guess was for a require-related problem. If I replace the setTimeout with a direct call, it seems to trigger the issue for me, so it's also a race thing.

Your suggestion for wrapping in a require call fixes it for me. 
I think what's going on is that the cellFolding function (which is called by initGutter) references the custom CodeMirror mode `CodeMirror.fold.firstline`, which is only actually defined by the require call at the end of  `load_extension`. Really, the modes (`firstline-fold.js`, and the seemingly unused `magic-fold.js`) should be wrapped in correct require calls, such that they can be required by the extension directly. I'll submit a PR to do this, but @halflings, in the meantime, you should be ok with @juhasch's suggestion, even without the `setTimeout`, so just a simple

```javascript
require(['./firstline-fold'], initGutter);
```

**Comment by halflings** [comment]
When I load my notebook, I see this in the console:

![skarmavbild 2016-02-18 kl 18 25 08](https://cloud.githubusercontent.com/assets/1626936/13151986/01111896-d66d-11e5-8a7c-713c0ec1266b.png)

Unsure if this is related to the same issue or just something else.

**Comment by jcb91** [comment]
Ok, that looks like what I see @halflings, did you try replacing lines 197/198 as @juhasch suggested? I'm sorry, my PR wasn't correct, I've updated it now, in case it was that that you tried...

**Comment by halflings** [comment]
Is it lines 197/198 in `foldcode.js`? Because in my case it has only 150 lines.

**Comment by juhasch** [comment]
Look at PR #478. This should do it.
