### ISSUE TITLE
Conda install fails due to package conflict

### ISSUE THREAD

**Issue by dhpizza** [ipython-contrib/IPython-notebook-extensions#426]
Hi,
I'm trying to install the nbextensions following the instructions and get a package conflict:

     conda install --channel https://conda.anaconda.org/juhasch nbextensions
     Fetching package metadata: ......  
     Solving package specifications: .........................................
     Error: Unsatisfiable package specifications.  
     Generating hint: 
     [      COMPLETE         ]|#################################################################################| 100%

    Hint: the following packages conflict with each other:
       - nbextensions
       - python 2.7*

     Use 'conda info nbextensions' etc. to see the dependencies for each package.

Following the hint gets me nowhere:

     conda info nbextensions
     Fetching package metadata: ....
     Error: No packages found in current linux-64 channels matching: nbextensions

My system setting are: IPython 4.0.1, python 2.7.10
Any idea what's going wrong?

**Comment by kyrre** [comment]
same problem here. trying to install on Python 2.7.11, Jupyter 4.0.6, IPython 4.0.1

**Comment by hubitor** [comment]
Same here with Python 2.7.11 |Anaconda 2.4.1 (64-bit)| (default, Dec  7 2015, 14:10:42) [MSC v.1500 64 bit (AMD64)] and Jupyter 4.0.6...

**Comment by qobilidop** [comment]
Same here with Python 3.5.1, conda 3.19.0

**Comment by juhasch** [comment]
The Conda package is currently broken, sorry. I removed it on anaconda.org for now.

**Comment by juhasch** [comment]
Closing, aswe don't have a conda package for the extensions, at least for now.
