### ISSUE TITLE
Alternate pip-install

### ISSUE THREAD

**Issue by jfbercher** [ipython-contrib/IPython-notebook-extensions#449]
This is not really an issue, but a possible feature I already described in  PR #439 .  This works for me, but can anybody else try it, and/or comment on the pros and cons of the approach? 

## Another pip-install attempt
 I have worked out an alternative pip-install for the IPython-contrib collection. The idea is to make a small package that takes care of dependencies, and installs a script that in turn, can be used to download and install the current master. Installation of the distribution to the current user directories, configuration files and paths is then done by
```
Jupyter_nb_contribs.py install
```
and probably via 
```
Jupyter_nb_contribs.exe install
```
under windows. 

**Caution: for now, the installation still overwrites existing files..** If you have made modifications, then backup or simply rename your existing nbextensions directory. 

This package can be seen at https://github.com/jfbercher/Jupyter_contrib_nbextensions_install_utility and can be tried using
```
pip install https://rawgit.com/jfbercher/Jupyter_contrib_nbextensions_install_utility/master/dist/Jupyter_contrib_nbextensions_install_utility-0.0.1.tar.gz
```
Tests, comments, suggestions, PR are most welcome!

**Comment by jcb91** [comment]
Since #448 was merged, I guess we could close this issue now?

**Comment by jfbercher** [comment]
The idea was to create an install program that could be distributed eg in pypi and that would take care of installing/updating the current master. Since nobody have commented/tried it seems that there is no need for that and that #448 is enough. Thus we can close.

**Comment by jcb91** [comment]
Aha! Sorry, I'd misunderstood (or not read properly :anguished:). Actually, I think this is a good idea, I've been thinking quite a bit recently about a pip install. I'll have a look when I get a chance...

**Comment by jcb91** [comment]
My mistake, misunderstood again, it seems this was essentially the install mechanism we have now, but available as a separate package...
