### ISSUE TITLE
Codefolding Error

### ISSUE THREAD

**Issue by diego898** [ipython-contrib/IPython-notebook-extensions#487]
I am having some strange problems with a code-folding extension where sometimes it would work, sometimes it wouldn't. I searched here and saw #422, went ahead and made the changes but that didn't fix it for me. So, I went ahead and deleted/cloned this repository again and ran `python setup.py install` again, started `jupyter notebook` and navigated to my `/nbextensions/` and I see codefolding is sitll enabled. I disabled/enabled it again and loaded up a notebook but I get the following: 

```
main.min.js:24082 Default extension for cell metadata editing loaded.
main.min.js:24168 Raw Cell Format toolbar preset loaded.
main.min.js:24216 Slideshow extension for metadata editing loaded.
main.min.js:28971 actions jupyter-notebook:find-and-replace does not exist, still binding it in case it will be defined later...
main.min.js:12109 Loading extension: usability/toc/main
http://localhost:8888/nbextensions/codefolding.js?v=20160222101811 Failed to load resource: the server responded with a status of 404 (Not Found)
main.min.js:12132 Failed to load extension: Array[1] Error: Script error for "nbextensions/codefolding"(…)(anonymous function) @ main.min.js:12132
main.min.js:12109 Loading extension: usability/chrome-clipboard/main
main.min.js:23370 Session: kernel_created (d5ffa412-12fa-41c6-8eff-61e5d8c10255)
main.min.js:22673 Starting WebSockets: ws://localhost:8888/api/kernels/6ccdc32a-47a7-4225-b4ad-a108b10124ba
main.min.js:12109 Loading extension: usability/codefolding/main
main.min.js:22329 Kernel: kernel_connected (6ccdc32a-47a7-4225-b4ad-a108b10124ba)
main.min.js:22329 Kernel: kernel_ready (6ccdc32a-47a7-4225-b4ad-a108b10124ba)
main.min.js:12109 Loading extension: widgets/notebook/js/extension
extension.js?v=20160222101811:81 loaded widgets
my_notebook.ipynb:1 Font from origin 'null' has been blocked from loading by Cross-Origin Resource Sharing policy: Invalid response. Origin 'http://localhost:8888' is therefore not allowed access.
```

**Comment by jcb91** [comment]
So, it seems from the log you have two different `codefolding` extensions enabled: the id `nbextensions/codefolding`, which fails to load, as expected, since it's not the correct path, and the id `usability/codefolding/main`, which looks from the log like it loads ok.
 You can deactivate the incorrect path using 
```
from notebook.services.config import ConfigManager
cm = ConfigManager()
# update with None, not False, to disable auto loading
cm.update('notebook', {"load_extensions": {"nbextensions/codefolding": None}})
```

Finally, is codefolding actually working for you? There don't seem to be other errors in the console log that would suggest it's broken in the manner of #422.

**Comment by diego898** [comment]
Hm. Oddly enough, it does indeed work now. Im a bit confused about how that happened. Either way, after running what you suggested I get the following: 
```
{'load_extensions': {'codefolding': True,
  'usability/chrome-clipboard/main': True,
  'usability/codefolding/main': True,
  'usability/toc/main': True}}
```

I still see two entries for codefolding?

**Comment by jcb91** [comment]
Ah, apologies, I got it wrong, it should have been

```python
from notebook.services.config import ConfigManager
cm = ConfigManager()
# update with None, not False, to disable auto loading
cm.update('notebook', {"load_extensions": {"codefolding": None}})
```

**Comment by diego898** [comment]
thanks for the help! It now produced 
```
{'load_extensions': {'usability/chrome-clipboard/main': True,
  'usability/codefolding/main': True,
  'usability/toc/main': True}}
```

**Comment by jcb91** [comment]
You're welcome. Ace. And codefolding works as expected in the loaded notebook?

**Comment by diego898** [comment]
As of right now yes! I will report back if anything changes

**Comment by jcb91** [comment]
Great :smile:
