### ISSUE TITLE
Feature Request - Add Scratchpad

### ISSUE THREAD

**Issue by j9ac9k** [ipython-contrib/IPython-notebook-extensions#496]
Minrk just created the scratchpad notebook extension (see here: https://github.com/minrk/nbextension-scratchpad )

This would be a great addition to the nbextensions repo here.

**Comment by jcb91** [comment]
Sure, assuming minrk would be ok with this, you'd be welcome to submit a PR, I'm sure

**Comment by minrk** [comment]
AOK :+1:

**Comment by juhasch** [comment]
Merged.
