### ISSUE TITLE
conda build fails with "RuntimeError: Setuptools downloading is disabled in conda build."

### ISSUE THREAD

**Issue by knub** [ipython-contrib/IPython-notebook-extensions#497]
Hi,

I have a freshly installed Anaconda (`conda 3.19.3`), installed Jupyter and now want to install the extensions.
When I run `conda build IPython-notebook-extensions`, I get the following error:

    RuntimeError: Setuptools downloading is disabled in conda build. Be sure to add all dependencies in the meta.yaml  url=https://pypi.python.org/simple/pyyaml/r
    Command failed: /bin/bash -x -e /home/knub/anaconda3/conda-bld/work/conda_build.sh

Here's some more of the console output, please tell me, when you need more:

    BUILD START: nbextensions-master-py35_0
    Using Anaconda Cloud api site https://api.anaconda.org
    Fetching package metadata: ......
    Solving package specifications: ...................................................
    The following NEW packages will be INSTALLED:

        decorator:        4.0.9-py35_0 
        ipykernel:        4.2.2-py35_0 
        ipython:          4.1.1-py35_0 
        ipython_genutils: 0.1.0-py35_0 
        jinja2:           2.8-py35_0   
        jsonschema:       2.4.0-py35_0 
        jupyter_client:   4.1.1-py35_0 
        jupyter_core:     4.0.6-py35_0 
        libsodium:        1.0.3-0      
        markupsafe:       0.23-py35_0  
        mistune:          0.7.1-py35_0 
        nbconvert:        4.1.0-py35_0 
        nbformat:         4.0.1-py35_0 
        notebook:         4.1.0-py35_0 
        openssl:          1.0.2f-0     
        path.py:          8.1.2-py35_1 
        pexpect:          3.3-py35_0   
        pickleshare:      0.5-py35_0   
        pip:              8.0.2-py35_0 
        psutil:           3.4.2-py35_0 
        ptyprocess:       0.5-py35_0   
        pygments:         2.1.1-py35_0 
        python:           3.5.1-0      
        pyzmq:            15.2.0-py35_0
        readline:         6.2-2        
        setuptools:       20.1.1-py35_0
        simplegeneric:    0.8.1-py35_0 
        sqlite:           3.9.2-0      
        terminado:        0.5-py35_1   
        tk:               8.5.18-0     
        tornado:          4.3-py35_0   
        traitlets:        4.1.0-py35_0 
        wheel:            0.29.0-py35_0
        xz:               5.0.5-1      
        zeromq:           4.1.3-0      
        zlib:             1.2.8-0      

    Linking packages ...
    [      COMPLETE      ]|#########################################################################################################################################| 100%
    Removing old work directory
    checkout: 'master'
    Cloning into '/home/knub/anaconda3/conda-bld/work'...
    done.
    Already on 'master'
    Your branch is up-to-date with 'origin/master'.
    ==> git log -n1 <==

    commit b508b0ffbda62ac935088f57b579bc9122743e88
    Merge: d2d6069 3a23c4e
    Author: Juergen Hasch <juergen.hasch@gmail.com>
    Date:   Mon Feb 22 17:43:11 2016 +0100

        Merge pull request #478 from jcb91/bugfix/codefolding
        
        bugfix in `nbextensions/usability/codefolding`…

    ==> git describe --tags --dirty <==

    before-4.x-reorg-345-gb508b0f

    ==> git status <==

    On branch master
    Your branch is up-to-date with 'origin/master'.

    nothing to commit, working directory clean

    Package: nbextensions-master-py35_0
    [...]

**Comment by juhasch** [comment]
Building conda packages currently doesn't work. Hopefully there will be a fix in the future.

**Comment by knub** [comment]
Maybe remove it from the README.md then, or add a note, that it does not work currently?

**Comment by juhasch** [comment]
Good idea. PR #500
