### ISSUE TITLE
toc2: long headlines blow up the toc to cover more than half of the screen

### ISSUE THREAD

**Issue by janschulz** [ipython-contrib/IPython-notebook-extensions#503]
The ToC2 widget has no max size -> adding a really long headline will inflate the toc over the complete windows. ToC1 had a [`max-width:230px;`](https://github.com/ipython-contrib/IPython-notebook-extensions/blob/master/nbextensions/usability/toc/main.css#L24), which was used on [my monitor to fill the right side until the border of the code cells](https://github.com/minrk/ipython_extensions/pull/44) so no code were covered by the Toc. IMO this should be reintroduced or the text used for the links in the ToC should be cut at a configurable length (`really long Headline` -> `really long He...`)

[Edit: not anymore happening...]~~To not forget it: The current ToC2 seems to slow down md rendering -> See https://github.com/ipython-contrib/IPython-notebook-extensions/pull/488#issuecomment-189359869 -> not yet sure where this comes from and is currently investigated in the merged PR issue~~[/]

**Comment by JanSchulz** [comment]
Ok, it seems I can resize the toc, but there seems to be a bug that will not let me drag the ToC but select text in the Toc. I could remove this "effect" by reloading the complete notebook.

**Comment by jfbercher** [comment]
toc2 still has a max-width, but which was increased to 600px in PR #472. This number may be indeed to large, especially for small screens. We can go back to the previous value or set max-width as a % of the container. Will try that later.

**Comment by jcb91** [comment]
You could also try the new css viewport units, vw/vh

**Comment by janschulz** [comment]
This is fixed: toc2 is now resizeable and then it brakes the headline according to the size of the toc widget.
