### ISSUE TITLE
Copy/Paste extension and collapsible headings

### ISSUE THREAD

**Issue by juhasch** [ipython-contrib/IPython-notebook-extensions#516]
Copy and paste works, but the +/- icons are missing:
![copypaste](https://cloud.githubusercontent.com/assets/2445216/13555766/3baabd90-e3c9-11e5-9ef1-2fb34b0a3eb9.png)

Paste operation:
```Javascript
var new_cell_data = JSON.parse(data[ix]);
var new_cell = IPython.notebook.insert_cell_below(new_cell_data.cell_type);
new_cell.fromJSON(new_cell_data);
```

@jcb91 : Any idea what I need to do to display the icons after pasting a cell from clipboard ?

**Comment by jcb91** [comment]
Hmm, strange. Generally the icons are generated when the `rendered.MarkdownCell` event fires, so I would expect this to work, since the fromJSON call should result in a render. As an unsatisfying temporary work around, simply re-executing the markdown should do it, but I'll take a look properly when I get a chance...

**Comment by juhasch** [comment]
Interestingly, unrendering and then rendering the markdown cell does not help.

**Comment by jcb91** [comment]
Oh! That's even more strange! I'm out of ideas for now then, I'll investigate. And you used the JavaScript in a code cell to insert the copied cells? Or is it from console/other extension?

**Comment by juhasch** [comment]
Seems like the `collapsible_headings_toggle` is not created for a copied cell:
![heading](https://cloud.githubusercontent.com/assets/2445216/13556579/511ed558-e3dd-11e5-992e-3f740493ba23.png)

![elements](https://cloud.githubusercontent.com/assets/2445216/13556571/271f11fa-e3dd-11e5-8030-f8ec6060a9a6.png)

Looks like I need to do more than just calling `.fromJSON()` in `chrome-clipboard/main.js`

**Comment by jcb91** [comment]
Strange. What *should* happen, is that the `rendered.MarkdownCell` event callback should call `update_heading_cell_status` (see [nbextensions/usability/collapsible_headings/main.js#L603](https://github.com/ipython-contrib/IPython-notebook-extensions/blob/master/nbextensions/usability/collapsible_headings/main.js#L603)), which then produces the toggle. For some reason, it seems that either that event isn't being fired, or the cell isn't identified as being a heading...

**Comment by juhasch** [comment]
Found it!. I need to do a `new_cell.execute();`. This makes it work!

**Comment by jcb91** [comment]
Weird. But the rendering didn't do it? Because, in the latest version, the render event should be doing the triggering, and that's the execute triggers anyway... but anyway, if it works ok for you now, that's good. Is any change needed/useful?

**Comment by juhasch** [comment]
See PR #518

**Comment by jcb91** [comment]
:+1:
