### ISSUE TITLE
whishlist: extension which adds styling to all tables

### ISSUE THREAD

**Issue by JanSchulz** [ipython-contrib/IPython-notebook-extensions#519]
The tables in a notebook are ugly by default. This here changes it:

```R
bootstrapify_tables <- function(){
    display_html('<style>table.table, table.table tr, table.table td, table.table th {border: 0}
table.table-nonfluid {width: auto !important;}</style>')
    display_html('<script>
bootstrapify = function(){
   // a table which was handled by pandoc
   $("tr.header").parent("thead").parent("table").addClass("table table-condensed table-nonfluid");
   // a markdown table as it appears in a markdown cell
   $("div.text_cell div.inner_cell div.rendered_html table").addClass("table table-condensed table-nonfluid");
};
$([IPython.events]).on("notebook_loaded.Notebook", bootstrapify);
$([IPython.events]).on("kernel_ready.Kernel", bootstrapify);
$([IPython.events]).on("output_appended.OutputArea", bootstrapify);
$([IPython.events]).on("rendered.MarkdownCell", bootstrapify);
</script>')
}
bootstrapify_tables()
```

I'm not sure if that is possible, but it would be nice if there would be an extension which would add such html by default and also add it to exported notebooks (at least the html ones). Maybe with an option to also handle the default pandas tables...

[Here is the whishlist bug in jupyter notebook to add it to the notebook per default: https://github.com/jupyter/notebook/issues/1182]

**Comment by jcb91** [comment]
It looks pretty much like you've done the bulk of the work to turn it into an extension already! I'll stick in a PR shortly.

**Comment by JanSchulz** [comment]
Unfortunately, it looks like it doesn't work: 

it seems that 

```
$([IPython.events]).on("output_appended.OutputArea", bootstrapify);
```

is not called when the output is already added to the document, at least it always keeps the last displayed table un-beautified :-( Is there any way to get a handle to the inserted html during the callback? Would be much easier to just `s/<table/<table class="..." /g` in the inserted string...

**Comment by jcb91** [comment]
hmm. Not sure. I spent a while looking at output for the execute_time extension, and couldn't find an event that worked reliably, so ended up patching the kernel execute reply...

**Comment by jcb91** [comment]
So you're attempting to catch pandocs tables, which are output as html, is that right? If you have an example notebook I could run (I have an R kernel, but no knowledge of R), that'd make diagnosis a bit easier. If you're looking at markdown rendering, part of the problem is that it's done asynchronously, so the event is fired potentially before the html elements are generated...

**Comment by JanSchulz** [comment]
Yes, but the easiest thing is simple add a markdown cell and add a table there.

After the comment of minrk in the notebook issue, I'm now using 

```
    html <- '<style>table.table, table.table tr, table.table td, table.table th {border: 0}
table.table-nonfluid {width: auto !important;}</style>'
    js <- '<script>
bootstrapify = function(){
   $(".rendered_html table").addClass("table table-condensed table-nonfluid");
   n_pandoc = $("tr.header").parent("thead").parent("table").length;
   n_md = $("div.text_cell div.inner_cell div.rendered_html table").length
   n_rendered = $(".rendered_html table").length
   console.log ("beautified "+ n_pandoc + " + " + n_md + " + " + n_rendered + " tables (pandoc + md + rendered) ...");
};
$([IPython.events]).on("notebook_loaded.Notebook", bootstrapify);
$([IPython.events]).on("kernel_ready.Kernel", bootstrapify);
$([IPython.events]).on("output_appended.OutputArea", bootstrapify);
$([IPython.events]).on("rendered.MarkdownCell", bootstrapify);
</script>'
```

If you use a python kernel, then wrapping the string in a  `IPython.display.HTML` ala 

```
HTML("""<style>table.table, table.table tr, table.table td, table.table th {border: 0}
table.table-nonfluid {width: auto !important;}</style>
<script>
bootstrapify = function(){
   $(".rendered_html table").addClass("table table-condensed table-nonfluid");
   n_pandoc = $("tr.header").parent("thead").parent("table").length;
   n_md = $("div.text_cell div.inner_cell div.rendered_html table").length
   n_rendered = $(".rendered_html table").length
   console.log ("beautified "+ n_pandoc + " + " + n_md + " + " + n_rendered + " tables (pandoc + md + rendered) ...");
};
$([IPython.events]).on("notebook_loaded.Notebook", bootstrapify);
$([IPython.events]).on("kernel_ready.Kernel", bootstrapify);
$([IPython.events]).on("output_appended.OutputArea", bootstrapify);
$([IPython.events]).on("rendered.MarkdownCell", bootstrapify);
</script>
""")
```

should be enough.

**Comment by jcb91** [comment]
I have what seems to be a more-or-less working version on my bootstrapify_tables branch: [jcb91@bootstrapify_tables](https://github.com/jcb91/IPython-notebook-extensions/tree/bootstrapify_tables)

**Comment by JanSchulz** [comment]
@jcb91 Damn, overlooked this and created my own: https://github.com/ipython-contrib/IPython-notebook-extensions/pull/524 (but it doesn't work currently, no idea why: the the file is loaded, but the real content is never called?)

**Comment by juhasch** [comment]
OK, so which one should we merge ?

**Comment by jcb91** [comment]
Yep, assuming my problems with `rendered.MarkdownCell` events firing before the markdown DOM elements were added are no longer happening (I'm starting to doubt it ever did happen, but then it was by nature a funny race condition, so it's difficult to tell), then Jan's has the advantage of only updating the currently rendering cell, and not waiting before doing it.
