### ISSUE TITLE
template path set twice

### ISSUE THREAD

**Issue by JanSchulz** [ipython-contrib/IPython-notebook-extensions#523]
I get the following error in the log after a reinstall of the extensions

```
[W 11:20:01.819 NotebookApp] Collisions detected in jupyter_notebook_config.py and jupyter_notebook_config.json config files. jupyter_notebook_config.json has higher priority: {
      "Exporter": {
        "template_path": "['.', 'C:\\\\Users\\\\jschulz\\\\AppData\\\\Roaming\\\\jupyter\\\\templates'] ignored, using ['C:\\\\Users\\\\jschulz\\\\AppData\\\\Roaming\\\\jupyter\\\\templates']"
      }
    }
```

I removed one (in the json) before the install and it was there again after the install, so it seem that the extension installer is to be blamed...

**Comment by jcb91** [comment]
Well, the json is recreated by the installer, but it seems that we also write the key into the python config...
