### ISSUE TITLE
Cannot see /nbextensions/ in jupyterhub

### ISSUE THREAD

**Issue by rickyking** [ipython-contrib/IPython-notebook-extensions#527]
Hi,

I have configure a jupyterhub server with PAM login.
I can login into jupyterhub and use the code below to enable the extension.
```python
import notebook
notebook.nbextensions.check_nbextension('usability/collapsible_headings', user=True)
E = notebook.nbextensions.EnableNBExtensionApp()
E.enable_nbextension('usability/collapsible_headings/main')
```

But I have no access to http://webnode:8000/user/yjin/nbextensions which returns 404, however, http://webnode:8000/user/yjin/nbextensions/config/main.js is accessible.

Thanks for your help...

**Comment by jcb91** [comment]
This may be down to the fact that the `nbextensions/` config page is implemented by a server-side python extension, not just javascript. As a result, you'll need to have it enabled by the server, which requires editing the python config file read by the server on start to add the extension to the path, and enable it). I'm not familiar with how jupyterhub actually does any of that, so it's possible you (as a user) may not have sufficient privileges to do it. If you don't have such privileges, and can't convince whoever does that the extension is a neat thing to have, then you can still configure extensions manually, but it's a bit of a pain. I'm happy to try to help in either situation

Any thoughts?

**Comment by rickyking** [comment]
Yes I have the root privilege.

**Comment by jcb91** [comment]
Ok, well, as I say, I haven't actually tried jupyterhub, but, from reading the docs at [jupyter/jupyterhub/docs/source/getting-started.md](https://github.com/jupyter/jupyterhub/blob/5d140fb889e61703b0d150a841fb6f83cbece7f7/docs/source/getting-started.md), it sounds like the single-user Jupyter servers are started using the same config as usual, so the first thing to check is whether you can get the `/nbextensions` url form a single-user server started in the same place that your hub's Spawner spawns them...

**Comment by jcb91** [comment]
I should mention, in order for the server-side extension to load, it is copied to the `extensions` directory by the install script, and then the single-server python configuration file is altered by the configure script to add it to the path (see [configure_nbextensions.py#L46](https://github.com/ipython-contrib/IPython-notebook-extensions/blob/1c2b8bcbad751792ae9ca7cf07f9d5efe87e284d/configure_nbextensions.py#L46)) and the json config edited in order to enable it (see [#L156-L157](https://github.com/ipython-contrib/IPython-notebook-extensions/blob/1c2b8bcbad751792ae9ca7cf07f9d5efe87e284d/configure_nbextensions.py#L156-L157)).

**Comment by rickyking** [comment]
Thanks I will check that out and come back later.

**Comment by akaihola** [comment]
There was also the thread [IPython-notebook-extensions and Jupyterhub](https://groups.google.com/d/msg/jupyter/W-ZSydNi5vY/6gc466JVBwAJ) in the Project Jupyter discussion group in February.

**Comment by jcb91** [comment]
This is related to #617, and is basically tied up with our less-than perfect installation scripts. I'm going to close this as #617 has rather more detail.

Another issue to add to the list which would be more satisfyingly fixed by #626. 😜

**Comment by prerakmody** [comment]
For a complete overview on getting started with jupyterhub, I wrote up a [gist](For a complete overview on getting started with jupyterhub, I wrote up a gist.)
1. Jupyerhub installation
2. Nginx configuring
3. Jupyter notebook extensions (with help from the above)

**Comment by Al2a2d2m** [comment]
a more simple way to install and get nbextension tab in jupyterhub 

1- open a jupyter notebook with your account on jupyterhub
install nbextensions as it was for a regular jupter installation from this notebook using the following code inside a cell
`! jupyter contrib nbextension install --user
` in a another cell, enable the tab:
`! jupyter nbextensions_configurator enable --user
`we are done, restart your server

**Comment by VinayChaudhari1996** [comment]
This is located in  **EDIT < nbextension**

![screenshot 87](https://user-images.githubusercontent.com/42869040/47523374-819c8980-d8b5-11e8-9e0a-6c99bacf4064.png)

**Comment by VinayChaudhari1996** [comment]
**What is this error ?**   nbextension cant be enable ! 

_

> (This nbextension's require url (zenmode/main) is referenced by two different yaml files on the server. This probably means that there are two installations of the same nbextension in different directories on the server. If they are different, only one will be loaded by the notebook, and this may prevent configuration from working correctly. Check the jupyter notebook server log for the paths of the relevant yaml files.)

_

![screenshot 88](https://user-images.githubusercontent.com/42869040/47523551-f4a60000-d8b5-11e8-8aa8-636424a1080f.png)
