### ISSUE TITLE
Lingering NBextensions resulting in duplicate menus

### ISSUE THREAD

**Issue by ruxi** [ipython-contrib/IPython-notebook-extensions#529]
Hi,

I tried to install NBextension via the pip method (didn't work, /nbextension resulted in 404 error) and then by git clone + setup.py (which did work). Now there are some duplicate menus in /nbextension. 

![image](https://cloud.githubusercontent.com/assets/6733446/13687053/bbe999d2-e6de-11e5-9c02-34251d8c57b8.png)

The source of the duplication appears to be older notebook 3.x extensions that have lingered from previous installation attempts.

![image](https://cloud.githubusercontent.com/assets/6733446/13687219/ab07a306-e6df-11e5-9508-18f1f3a1f9c1.png)
 
Issue #505 suggests deleting ~/.jupyter/nbconfig/notebook.json may help. Attempted, but no change.

Any suggestions on how to resolve? (remove the old extensions)

Thanks

**Comment by jcb91** [comment]
Hi there. So, #505 deals with an extension which is enabled (i.e. set to load in json config), but no longer present in the file system. In contrast, what you appear to have is a situation in which you have two copies of at least some of the extensions, presumably in separate locations in the file system (e.g. perhaps `/usr/local/share/jupyter` and `~/.jupyter`).

What you'll need to do is find the older version on your file system, and probably manually remove them (unfortunately!). One thing that strikes me as significant is that you have two sets of python markdown enabled, so the difference between the two paths for those should give you some idea of where your duplicates are hiding.

You can use the following python snippet (adapted from the config extension which provides the nbextensions page) to find the paths of every yaml file:

```python
from __future__ import print_function
import os.path
from itertools import chain
from jupyter_core.paths import jupyter_data_dir
from notebook.nbextensions import _get_nbext_dir as get_nbext_dir

nbextension_dirs = (get_nbext_dir(), os.path.join(jupyter_data_dir(), 'nbextensions'))
yaml_files = []
for root, dirs, files in chain.from_iterable(os.walk(nb_ext_dir, followlinks=True) for nb_ext_dir in nbextension_dirs):
    for filename in files:
        if filename.endswith('.yaml'):
            yaml_files.append(os.path.join(root, filename))

for yaml_path in sorted(yaml_files):
    print(yaml_path)
```

**Comment by jcb91** [comment]
of course, it might be simpler, I suppose, to just nuke all directories in the `nbextension_dirs` tuple as returned in the snippet above, and then just reinstall from scratch in whatever way works best for you - depends on your preference, and whether you've got any nbextensions not from the repository that you wish to preserve :stuck_out_tongue_closed_eyes:

**Comment by ruxi** [comment]
Wow, thanks jcb91! 

All the legacy extensions were neatly in

```bash
/.local/share/jupyter/nbextensions/IPython-notebook-extensions/
```

Deleting the folder removed the duplicates. Surprisingly painless!


![image](https://cloud.githubusercontent.com/assets/6733446/13692965/a2a85954-e70b-11e5-842c-c25ca96d2836.png)

**Comment by JanSchulz** [comment]
I think we should add a uninstall before reinstall: during development of the table beautifier, i move the thing around and ended up with three copies of the thing :-(

IMO in the installer should: 
* not only copy the files, but record each copied file in a special file (e.g. `ipython-notebook-extension_files.txt`)
* before install, check if the file exists and if so, first remove all files recorded in there

**Comment by jcb91** [comment]
@ruxi you're welcome, glad it worked easily for you :smile:
@JanSchulz I guess you mean you ended up with multiple copies in the filesystem by installing multiple times over? You're right, we don't currently have any way to remove extensions provided by an earlier install of this repo, and a simple list of files installed would be pretty easy to implement...

**Comment by jcb91** [comment]
Added a PR for this in #569
