### ISSUE TITLE
LaTeX_envs changing standard text font fize

### ISSUE THREAD

**Issue by aguirreeng** [ipython-contrib/IPython-notebook-extensions#552]
I've installed the extensions and I'm using the LaTeX_envs. It is working but is changing the standard font size throughout the notebook. I've added some screenshots of a notebook with and without the module activated.
Any help on how to solve this?

Here is a sample with the LaTeX_envs deactivated:
![no-latex-envs](https://cloud.githubusercontent.com/assets/11059665/13949797/e0d93326-f005-11e5-8e4a-2aa427992257.png)

Here is a sample with the LaTeX_envs activated:
![latex-envs](https://cloud.githubusercontent.com/assets/11059665/13949781/c49fd5a2-f005-11e5-882f-a8dd1ea98411.png)

Cheers and thanks for the extensions!

**Comment by jfbercher** [comment]
The fonts are defined in latex_envs.css. 
You just have to comment/update the fonts definitions in that file. 

Beware that for now, customized css files are overwrited when the extension is updated. That is the way it is, so keep a copy.

**Comment by jcb91** [comment]
Specifically, this seems to be a result of [nbextensions/usability/latex_envs/latex_envs.css#L180-L182](https://github.com/ipython-contrib/IPython-notebook-extensions/blob/17b9a253ed8026d7d1bc7f6caea359ff9c20877d/nbextensions/usability/latex_envs/latex_envs.css#L180-L182). It does seem a little strange to be setting fonts and sizes for things which are styled already by core Jupyter. @jfbercher do you think `latex_envs` could do without the lines in question (or even the whole `div.text_cell_render` selector), or is it needed for some part of the proper functioning? If it's needed, perhaps the selector could be made more specific?

@aguirreeng, completely off-topic, but I'm curious: what's providing the coloured squares where the notebook name normally sits? What are they for?

**Comment by aguirreeng** [comment]
@jcb91, I've just applied the effect to the images covering the names of the notebooks, on the actual notebooks the names are still there, :-)

**Comment by jcb91** [comment]
Haha ok! The colours made it look too artistic to be that simple :)

**Comment by jfbercher** [comment]
@jcb91 There should be no problem removing the whole section 'GENERAL CONFIG'. These were just my personal preferences. They can go to custom.css instead. I'll do a small update (or anybody can do it of course).

**Comment by jcb91** [comment]
@jfbercher yeah, that would be nice, I think, to adhere to the [principle of least astonishment](https://en.wikipedia.org/wiki/Principle_of_least_astonishment) :stuck_out_tongue_closed_eyes: Thanks!

**Comment by jcb91** [comment]
fixed by #572
