### ISSUE TITLE
Pymarkdown preprocessor nbconvert issue

### ISSUE THREAD

**Issue by BreitA** [ipython-contrib/IPython-notebook-extensions#561]
Hi,

I tried to follow your instruction on the https://github.com/ipython-contrib/IPython-notebook-extensions/wiki/python-markdown

I can't find pymdpreprocessor.py at all even by downloading the git repo.
I found pre_pymarkdown.py though so it might be a new name for it. 
What are the current steps to make this work? 

My aim is to generate multiple reports using jupyter nbconvert and your tool to change markdown text with variables. 

I use python 2.7

**Comment by jcb91** [comment]
Hi there. Apologies, you are correct, the `pre_pymarkdown.py` is the current version, this is simply a case of the wiki being out of date (often extensions readme files get updated without corresponding updates being made to the wiki).

Essentially, to get the preprocessor to work with nbconvert, config files need to tell nbconvert to load it, and alter the path so it can find it.

The simplest way to get all of that done is by running `python setup.py install` in the git repo you've downloaded. Take note that it modifies config files for both jupyter notebook and nbconvert, and also copies all the repo nbextension, template etc files into your `jupyter --data-dir`, blindly overwriting anything which already exists there with colliding names. The install script permanently modifies nbconvert convert config in [configure_nbextensions.py#L139-L145](https://github.com/ipython-contrib/IPython-notebook-extensions/blob/9a345e6cc93fe9cd02221b03bfd2b626e6eb29d8/configure_nbextensions.py#L139-L145).

Does that make sense?

**Comment by jcb91** [comment]
Actually, in this case, the readme was also still wrong... fixed in #562.

**Comment by BreitA** [comment]
ok I did everything from clean install.
I installed from git
I modified my jupyter_nbconvert_config.py like this :

#--- nbextensions configuration ---
import sys
sys.path.append('C:\\Users\\Antoine\\AppData\\Roaming\\jupyter\\extensions')
#--- nbextensions configuration ---
c=get_config()
c.Exporter.preprocessors = [ 'pre_pymarkdown.PyMarkdownPreprocessor' ]


I run a notebook named test.ipynb looking like this
import numpy as np

a=np.random.random()

print a

out :0.112119686875

markdown : 0.11211968687522289 ( this is the markdown {{a}})


and then i run the following command

#jupyter nbconvert --to notebook --execute test.ipynb 

I retrieve a test.nbconvert.ipynb notebook

in this notebook I hope there is a new random number 
but

import numpy as np

a=np.random.random()

print a

out : 0.876435812858

0.11211968687522289 -> {{a}}  has been replaced by the markdown '0.11211968687522289' invariant from the inital notebook 

So pymarkdown seems to not work as intended if I understand well.

**Comment by jfbercher** [comment]
Why do you do the conversion notebook to notebook, with the exec flag? 
What happens with the --execute is that code cells are executed and their output updated. But since the notebook is not in the browser, there is no javascript extensions active, and the metadata in the cells, thus in markdown, are not updated.

**Comment by BreitA** [comment]
Ok I was trying to do that to automate the generation of beautiful reports but it seems the extension is not adapted to what I want to do. Sorry to disturb you on this one. 

The most effective solution to my problem has been this one for those interested. 

http://guido.vonrudorff.de/ipython-notebook-code-output-as-markdown/

**Comment by jcb91** [comment]
@BreitA not a problem. To avoid depending on an installed markdown magic, you could also use (following your example)

```python
from IPython.display import display, Markdown
import numpy as np

display(Markdown('$ a = {}$'.format(np.random.random())))
```

**Comment by BreitA** [comment]
Thanks for the idea using directly markdown didn't know Ipython.display could do that .  
Will use that as this is cleaner solution to my problem !
