### ISSUE TITLE
Error loading nbextensions with pip install

### ISSUE THREAD

**Issue by tuanvu216** [ipython-contrib/IPython-notebook-extensions#576]
Using the pip install with Jupyter version 4.x gives me this error

```
Error loading server extension nbextensions
    Traceback (most recent call last):
      File "/Users/tvu/anaconda/lib/python2.7/site-packages/notebook/notebookapp.py", line 1005, in init_server_extensions
        mod = importlib.import_module(modulename)
      File "/Users/tvu/anaconda/lib/python2.7/importlib/__init__.py", line 37, in import_module
        __import__(name)
    ImportError: No module named nbextensions
```

**Comment by jcb91** [comment]
The pip install doesn't seem to work well for everyone, a number of people have had problems with it. You may find it easiest to run the `python setup.py install` from a cloned repo/downloaded archive. Alternatively, see below.

The error from the server log you quote indicates that:

* the `jupyter_notebook_config.json` config file was correctly modified to load the `nbextensions` server extension
* the `jupyter_notebook_config.py` file was not correctly modified to edit `sys.path` to allow the extension to be imported.

You can try to find the relevant `jupyter_notebook_config.py` config file using the following python snippet:

```python
import os
from jupyter_core.paths import jupyter_config_path

for p in jupyter_config_path():
    conf_path = os.path.join(p, 'jupyter_notebook_config.py')
    if os.path.exists(conf_path):
        print(conf_path)
```

**Comment by tuanvu216** [comment]
Hi @jcb91,

By cloning the repository again, and running this:

```
pip install --upgrade https://github.com/ipython-contrib/IPython-notebook-extensions/archive/master.zip --user
```

Everything seems to work fine now. I will close this issue then.

Thanks,
Tuan
