### ISSUE TITLE
nbextensions button does not go to correct URL if base_url is set

### ISSUE THREAD

**Issue by pybokeh** [ipython-contrib/IPython-notebook-extensions#582]
When I go to the GUI menu "Edit" --> "nbextensions", it routes me to http://localhost:8888/nbextensions/ when it should have routed me to http://localhost:8888/jupyter/nbextensions/ since my jupter_notebook_config.py file has this line:
    
    c.NotebookApp.base_url = '/jupter/'
    
So it looks like it doesn't take into account when the user has configured a base_url.

**Comment by pybokeh** [comment]
Apologies, perhaps this issue should have been opened at the jupyter notebooks repo?

**Comment by jcb91** [comment]
nope, this is the right place for it! Yep, this is just because I wrote the extension providing the menu item in a very short time, and neglected to support custom base_urls. I'll fix it shortly.

**Comment by jcb91** [comment]
That should hopefully fix it. Obviously, re-open if not!

**Comment by pybokeh** [comment]
Wow that was quick!  Will do, thanks!

**Comment by pybokeh** [comment]
I just upgraded and confirmed the button works correctly for me.  Thanks again!

**Comment by jcb91** [comment]
de nada 😄
