### ISSUE TITLE
Can't get Markdown to export rendered values

### ISSUE THREAD

**Issue by rfenner** [ipython-contrib/IPython-notebook-extensions#585]
I installed the extensions using the setup.py file but When exporting some python markdown it doesn't render the markdown output.
I'm using jupyter 4.0.6 with python 2.7
I had to fix the install.py error where FileNotFoundError is not available in python 2.7. I fixed it by adding at the after imports
```
try:
  FileNotFoundError
except NameError:
  FileNotFoundError = IOError.
```

Beyond that it installed fine

My jupyter_nbconvert_config.json looks like
`{
  "Exporter": {
    "preprocessors": [
      "pre_codefolding.CodeFoldingPreprocessor",
      "pre_pymarkdown.PyMarkdownPreprocessor"
    ],
    "template_path": [
      ".",
      "/Users/rfenner/Library/Jupyter/templates"
    ]
  },
  "NbConvertApp": {
    "postprocessor_class": "post_embedhtml.EmbedPostProcessor"
  },
  "version": 1
}`

If I followed the wiki and added the line for the preprocessor .py file I'd see a message about a conflict when running jupyter nbconvert.

For some reason it just doesn't seem to be running the preprocessor.
I did add the path to preprocessor to the PYTHONPATH as well

**Comment by juhasch** [comment]
Can you run nbconvert using the `--debug` option, i.e.
```
jupyter nbconvert test-markdown.ipynb --debug
```
and post the output ?

**Comment by rfenner** [comment]
[NbConvertApp] Config changed:
[NbConvertApp] {'NbConvertApp': {'log_level': 10}}
[NbConvertApp] Searching [u'/Users/rfenner/Downloads/IPython-notebook-extensions-master', '/Users/rfenner/.jupyter', '/Users/rfenner/Library/Enthought/Canopy_64bit/User/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files
[NbConvertApp] Attempting to load config file jupyter_config.py in path /etc/jupyter
[NbConvertApp] Attempting to load config file jupyter_config.json in path /etc/jupyter
[NbConvertApp] Attempting to load config file jupyter_config.py in path /usr/local/etc/jupyter
[NbConvertApp] Attempting to load config file jupyter_config.json in path /usr/local/etc/jupyter
[NbConvertApp] Attempting to load config file jupyter_config.py in path /Users/rfenner/Library/Enthought/Canopy_64bit/User/etc/jupyter
[NbConvertApp] Attempting to load config file jupyter_config.json in path /Users/rfenner/Library/Enthought/Canopy_64bit/User/etc/jupyter
[NbConvertApp] Attempting to load config file jupyter_config.py in path /Users/rfenner/.jupyter
[NbConvertApp] Attempting to load config file jupyter_config.json in path /Users/rfenner/.jupyter
[NbConvertApp] Attempting to load config file jupyter_config.py in path /Users/rfenner/Downloads/IPython-notebook-extensions-master
[NbConvertApp] Attempting to load config file jupyter_config.json in path /Users/rfenner/Downloads/IPython-notebook-extensions-master
[NbConvertApp] Attempting to load config file jupyter_nbconvert_config.py in path /etc/jupyter
[NbConvertApp] Attempting to load config file jupyter_nbconvert_config.json in path /etc/jupyter
[NbConvertApp] Attempting to load config file jupyter_nbconvert_config.py in path /usr/local/etc/jupyter
[NbConvertApp] Attempting to load config file jupyter_nbconvert_config.json in path /usr/local/etc/jupyter
[NbConvertApp] Attempting to load config file jupyter_nbconvert_config.py in path /Users/rfenner/Library/Enthought/Canopy_64bit/User/etc/jupyter
[NbConvertApp] Attempting to load config file jupyter_nbconvert_config.json in path /Users/rfenner/Library/Enthought/Canopy_64bit/User/etc/jupyter
[NbConvertApp] Attempting to load config file jupyter_nbconvert_config.py in path /Users/rfenner/.jupyter
[NbConvertApp] Attempting to load config file jupyter_nbconvert_config.json in path /Users/rfenner/.jupyter
[NbConvertApp] Loaded config file: /Users/rfenner/.jupyter/jupyter_nbconvert_config.py
[NbConvertApp] Loaded config file: /Users/rfenner/.jupyter/jupyter_nbconvert_config.json
[NbConvertApp] Config changed:
[NbConvertApp] {'NbConvertApp': {u'postprocessor_class': u'post_embedhtml.EmbedPostProcessor', 'log_level': 10}, u'Exporter': {u'preprocessors': [u'pre_codefolding.CodeFoldingPreprocessor', u'pre_pymarkdown.PyMarkdownPreprocessor'], u'template_path': [u'.', u'/Users/rfenner/Library/Jupyter/templates']}}
[NbConvertApp] Attempting to load config file jupyter_nbconvert_config.py in path /Users/rfenner/Downloads/IPython-notebook-extensions-master
[NbConvertApp] Attempting to load config file jupyter_nbconvert_config.json in path /Users/rfenner/Downloads/IPython-notebook-extensions-master
[NbConvertApp] Converting notebook /github/GCTools/development/analysis_scripts/test_pdf_export.ipynb to html
[NbConvertApp] Notebook name is 'test_pdf_export'
[NbConvertApp] Applying preprocessor: coalesce_streams
[NbConvertApp] Applying preprocessor: CSSHTMLHeaderPreprocessor
[NbConvertApp] Applying preprocessor: HighlightMagicsPreprocessor
[NbConvertApp] Applying preprocessor: CodeFoldingPreprocessor
[NbConvertApp] Applying preprocessor: PyMarkdownPreprocessor
[NbConvertApp] Attempting to load template full.tpl
[NbConvertApp] Loaded template full.tpl
[NbConvertApp] Attempting to load template full.tpl
[NbConvertApp] Loaded template full.tpl
[NbConvertApp] Writing 190518 bytes to test_pdf_export.html

Oddly enough that worked when i looked in the html it was converted. Seems to be when doing the download as from the file menu in the browser where it's failing.

**Comment by rfenner** [comment]
Here's the output when running as notebook server:
[D 14:01:06.216 NotebookApp] Applying preprocessor: coalesce_streams
[D 14:01:06.216 NotebookApp] Applying preprocessor: SVG2PDFPreprocessor
[D 14:01:06.216 NotebookApp] Applying preprocessor: LatexPreprocessor
[D 14:01:06.217 NotebookApp] Applying preprocessor: HighlightMagicsPreprocessor
[D 14:01:06.217 NotebookApp] Applying preprocessor: ExtractOutputPreprocessor
[D 14:01:06.218 NotebookApp] Attempting to load template article.tplx
[D 14:01:06.221 NotebookApp] Loaded template article.tplx
[D 14:01:06.221 NotebookApp] Attempting to load template article.tplx
[D 14:01:06.221 NotebookApp] Loaded template article.tplx
[I 14:01:06.452 NotebookApp] Writing 14323 bytes to notebook.tex
[I 14:01:06.452 NotebookApp] Building PDF
[I 14:01:06.452 NotebookApp] Running pdflatex 3 times: [u'pdflatex', u'notebook.tex']
[I 14:01:07.814 NotebookApp] PDF successfully created

**Comment by juhasch** [comment]
There is a difference if you export from within the notebook or from standalone nbconvert.
You need to add the `"Exporter"` stuff to `jupyter_notebook_config.json` in order to make it work there too.

Exporting notebooks is still a pain, IMO.

**Comment by rfenner** [comment]
Ok that helped. Copying the exporter config over into the notebook one worked. Now I just have to figure out where canopy is getting it's config from since it doesn't seem to be the .jupyter folder but it does pull in the enabled extensions.

**Comment by aleksandrkl** [comment]
Confirming that I was able to address the same issue (evaluating code in markdown for print) in Python 3.7.2 with the advice given in this thread.
