### ISSUE TITLE
missing depend on six

### ISSUE THREAD

**Issue by janschulz** [ipython-contrib/IPython-notebook-extensions#596]
It seems that the nbconvert stuff uses six, but when I install an env with nbconvert and notebook, six is not installed and therefore nbconvert to pdf fails: https://github.com/conda-forge/nbconvert-feedstock/issues/3

**Comment by jcb91** [comment]
yes, apologies, `six` is used in `extensions/pre_codefolding.py`, although to be honest, it could do without it fairly easily. I made a slightly more extensive investigation of dependencies in #595, but couldn't post away from wifi. Will update there.

**Comment by jcb91** [comment]
fixed in #598
