### ISSUE TITLE
Collapsible headings: nbcovert notebook

### ISSUE THREAD

**Issue by brecht-d-m** [ipython-contrib/IPython-notebook-extensions#605]
Is it possible to convert a notebook to HTML with collapsible headings still "enabled" in the converted HTML file? I tried to add ```"pre_collapsible_headings.CollapsibleHeadingsPreprocessor"``` to the preprocessors in ```jupyter_nbconvert_config.json```, but this seems not to do it (```jupyter nbconvert notebook_name.ipynb```). 

If it is possible, do I need to change/add other files?

**Comment by jcb91** [comment]
True, I tested the preprocessor recently and it doesn't work as intended.
I've made a fix in my trav branch, but haven't backported it yet. Will aim
to do it soon...

**Comment by brecht-d-m** [comment]
Your fix does indeed fix a part of my issue. What I'm truly looking for, is that the functionality that the collapsible headings extension has in the notebooks, is preserved in the exported HTML file. I mean that I could also collapse and uncollapse parts of the HTML file. Or is this not possible?

**Comment by jcb91** [comment]
Ah, I see! Sorry, I was a bit slow on the uptake there. Hmm. I'm not
completely sure, but I think it's maybe possible, given that jquery is (I
think?) included as a link in the output HTML. I'll have a think and see if
I can patch in some JavaScript through the preprocessor...

**Comment by jfbercher** [comment]
You can probably do this with a template like I suggested in #600 for collapsing outputs (jquery is included in full.tpl).
It will be nice :-)

**Comment by jcb91** [comment]
Ah yes, I knew I'd seen a reference to something similar recently somewhere
:)

**Comment by brecht-d-m** [comment]
A template did indeed solved it. If somebody is interested, I have put the code [here (template)](https://gist.github.com/brecht-d-m/01529f956bb90032508ff439f466325d) and [here (javascript file)](https://gist.github.com/brecht-d-m/88f5a989a1818191277852559f4c2b0c)

**Comment by jcb91** [comment]
@brecht-d-m interesting approach! It certainly seems rather more intuitive to place cells inside each other, though as you note, it does give rise to potential DOM-related issues for other templates/postprocessors/css etc.
