### ISSUE TITLE
toc2 links don't work when collapsible-headings is enabled

### ISSUE THREAD

**Issue by brunobeltran** [ipython-contrib/IPython-notebook-extensions#609]
Title says it all, haven't had time to dig into the cause, but figured I'd go ahead and report it.

**Comment by jcb91** [comment]
Thanks for the report. In what way do thy not work, just nothing happens when you click them? I suppose this may be a result of both extensions attempting to patch markdowncell render functions, and somehow interfering with each other, though nothing obvious springs to mind right now...

**Comment by brunobeltran** [comment]
Yeah they act just like they would if the links didn't exist. Since this
only appears to happen if the target section is hidden (i.e. collapsed), my
hypothesis is that this might require actually looking at what happens to
the link targets when they are in a collapsed section, and maybe some code
to open the section before jumping to the link if it's collapsed.

**Comment by jcb91** [comment]
Right, this is probably because cells in collapsed sections are `display:none`, so presumably won't show up as anchors for the links to point to...?

**Comment by brunobeltran** [comment]
So I guess it's a feature request for collapsible headings then. It should
register all anchors in the collapsed sections to some kind of JavaScript
hook that opens the subsection in question and scrolls to it when one is
referenced?

**Comment by jcb91** [comment]
Yep, sounds about right. Should hopefully be relatively simple...
