### ISSUE TITLE
Overlapping tags

### ISSUE THREAD

**Issue by ignaciomartin** [ipython-contrib/IPython-notebook-extensions#611]
All table contents labels (except the last) are overwritten each other:

![image](https://cloud.githubusercontent.com/assets/19220563/15532900/4e559334-2262-11e6-8706-ecd51c43a4ff.png)

`# Table of Contents
 <p><div class="lev2"><a href="#Ficheros-de-texto."><span class="toc-item-num">0.1&nbsp;&nbsp;</span><cite class="alert alert-danger">Ficheros de texto.</cite></a></div><div class="lev3"><a href="#Leer-de-ficheros-de-texto."><span class="toc-item-num">0.1.1&nbsp;&nbsp;</span><cite class="alert alert-warning">Leer de ficheros de texto.</cite></a></div><div class="lev4"><a href="#Función-open()."><span class="toc-item-num">0.1.1.1&nbsp;&nbsp;</span><cite class="alert alert-info">Función <em>open()</em>.</cite></a></div><div class="lev4"><a href="#Leer-un-fichero-completo."><span class="toc-item-num">0.1.1.2&nbsp;&nbsp;</span><cite class="alert alert-info">Leer un fichero completo.</cite></a></div><div class="lev4"><a href="#Leer-un-fichero-línea-por-línea."><span class="toc-item-num">0.1.1.3&nbsp;&nbsp;</span><cite class="alert alert-info">Leer un fichero línea por línea.</cite></a></div><div class="lev3"><a href="#Trabajando-con-ficheros-y-rutas."><span class="toc-item-num">0.1.2&nbsp;&nbsp;</span><cite class="alert alert-warning">Trabajando con ficheros y rutas.</cite></a></div><div class="lev4"><a href="#Información-de-ficheros."><span class="toc-item-num">0.1.2.1&nbsp;&nbsp;</span><cite class="alert alert-info">Información de ficheros.</cite></a></div><div class="lev4"><a href="#Interactuar-con-el-sistema-de-ficheros."><span class="toc-item-num">0.1.2.2&nbsp;&nbsp;</span><cite class="alert alert-warning">Interactuar con el sistema de ficheros.</cite></a></div><div class="lev3"><a href="#Escribiendo-en-ficheros."><span class="toc-item-num">0.1.3&nbsp;&nbsp;</span><cite class="alert alert-warning">Escribiendo en ficheros.</cite></a></div><div class="lev4"><a href="#Leer-y-escribir-un-arreglo-desde-y-hacia-un-fichero-."><span class="toc-item-num">0.1.3.1&nbsp;&nbsp;</span><cite class="alert alert-warning">Leer y escribir un arreglo desde y hacia un fichero .</cite></a></div>`

**Comment by jfbercher** [comment]
You have embedded special styles in titles (with classes like alert, warning etc). These create boxes that overlap the lines above or below. My only suggestion is that you should avoid this with this toc extension.  
We could sanitize the html links when building the toc content, but the consequence would be that we will lost simple styling (bold, italic, etc) and maths as well.

**Comment by jcb91** [comment]
Yep, as @jfbercher says, this is an issue with the css classes that you're using (which come from bootstrap alerts, see http://getbootstrap.com/components/#alerts), which add custom padding and margins. Is there a reason why you decided to use the alert classes? It seems like you'd have better results using the helper classes which define only the colours, without modifying padding or margins - see http://getbootstrap.com/css/#helper-classes-colors and http://getbootstrap.com/css/#helper-classes-backgrounds

**Comment by ignaciomartin** [comment]
Thanks @jfbercher  and @jcb91.
I replaced alert classes by helper classes and now all work fine.
