### ISSUE TITLE
Codefolding of cell magics no longer enabled

### ISSUE THREAD

**Issue by m7thon** [ipython-contrib/IPython-notebook-extensions#613]
The codefolding code for cell magics (starting with `%%`) is currently not enabled (it is still there, though). It used to be, but this somehow got lost in the reorganization commit [e3f2afa]. It seems this was partially re-enabled by the latest commit [3a23c4e] by adding back the relevant code as a requirement [here](https://github.com/ipython-contrib/IPython-notebook-extensions/blob/master/nbextensions/usability/codefolding/main.js#L198) but without enabling it by adding `CodeMirror.fold.magic` to the lines [here](https://github.com/ipython-contrib/IPython-notebook-extensions/blob/master/nbextensions/usability/codefolding/main.js#L113-L116).

Was there a reason for deactivating this feature, or was that just an oversight?

**Comment by juhasch** [comment]
I think it simply was an oversight. Care to make a pull request to enable this feature again ?
