### ISSUE TITLE
[Feature Request] [Collapsible Headings] Shortcut to add heading above/below

### ISSUE THREAD

**Issue by brunobeltran** [ipython-contrib/IPython-notebook-extensions#616]
A really slick UI feature that would save people a lot of annoyance would be a shortcut to add a heading at the current level above/below the current section. 

The most obvious use case is when you have two really long sections next to each other and want to add a section between. If you add a cell above the lower section title, the collapsible headings section (rightfully) expands the upper section. This then requires that you scroll to the bottom of the section to first add the desired section title, then usually back up again to collapse the accidentally expanded section. 

This seems silly, but in truly huge notebooks like the ones I use to organize my Ph.D. work, I end up temporarily reactivating Vimperator to navigate at that point, when collapsible-headings could in principle be enough to keep everything organized.

**Comment by jcb91** [comment]
Certainly possible, and sounds like a reasonable use-case. I guess we could add keyboard shortcuts and/or toolbar buttons easily enough, I'll take a look when I get a chance...

**Comment by jcb91** [comment]
@brunobeltran  any suggestions for button icons/shortcut keys?

**Comment by brunobeltran** [comment]
Similar to the Excel icon to add a row, but `# Title1`, `# Title 2`, etc instead of spreadsheet rows?

Link for reference [Excel Insert Row Icon](https://cdn.ablebits.com/_img-blog/insert-rows/excel-insert-icon.png)

Ideally the menu entry would be a drop down or list-like menu that lets you select from "add section  above", and "add section below", then adds a new markdown cell with `## Title` in it with the appropriate number of pound signs to match the level of the nearest parent cell of the currently highlighted cell, then highlights the new cell for editing of the title.

`Shift-A` and `Shift-B` aren't taken, so it seems like that's the obvious way to extend the current `a`, `b` shortcuts for adding a cell above and below.

Thanks a ton for putting time into this! If I finish up my current project in time, I'll make sure to lend a hand.

**Comment by jcb91** [comment]
Right, I haven't bothered making whole new icons, but currently (see PR #620) just gone with a `#` plus an arrow. If you fancy making some icons I'll be happy to include them. Toolbar buttons are optional, shortcuts default to `shift-a` and `shift-b` as you suggested, but are configurable as with the existing collapse/uncollapse/select shortcuts. I've also added items to the 'insert' menu, but didn't put in a dropdown yet (it seemed like it'd be more frustrating than useful, given only 2 items added to the menu). Let me know if/when you get a chance to test it 😊

**Comment by jcb91** [comment]
oh, also worth noting that I've swapped a lot of the parameter names from things like `collapsible_headings_shortcut_uncollapse` to `collapsible_headings.shortcuts.uncollapse`, which will mean you'll need to reconfigure any non-default settings for those options.

**Comment by jcb91** [comment]
@brunobeltran if this is working ok for you, I guess we can merge, since it's extra features rather than altering existing stuff...

**Comment by brunobeltran** [comment]
Was going to submit a fix actually, or you can add it. You need a
Jupyter.notebook.execute_cell() at line 595ish of main.js. That way, if you
add a cell below, Collapsible Headings registers it as a title before you
put the user into edit mode, preventing it from being "bury"'d inside of an
existing, closed section.

Not sure if this makes sense?
