### ISSUE TITLE
error in following documentation 

### ISSUE THREAD

**Issue by epifanio** [ipython-contrib/IPython-notebook-extensions#618]
Tring to configure the extension following [those instructions](https://github.com/ipython-contrib/IPython-notebook-extensions/wiki/Home-4.x-%28Jupyter%29) i got this error:

``` python
import notebook
E = notebook.nbextensions.EnableNBExtensionApp()
E.enable_nbextension('usability/codefolding/main')
```
I got the following error:

``` python
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-79dd84cd75e5> in <module>()
      1 import notebook
      2 E = notebook.nbextensions.EnableNBExtensionApp()
----> 3 E.enable_nbextension('usability/codefolding/main')

AttributeError: 'EnableNBExtensionApp' object has no attribute 'enable_nbextension'

```

**Comment by jcb91** [comment]
this can presumably be closed along with #617 now?

**Comment by jcb91** [comment]
I'm not really sure why this error ever occurred in the first place tbh - did you figure it out?

**Comment by epifanio** [comment]
I switched to anaconda after tring to debug my system python installation on debian.  The error is still the same. About  #617  I'll treopen it and add few more findings after debug.

**Comment by jcb91** [comment]
ok, so we should close this in favour of #617 then?

**Comment by jcb91** [comment]
Ah, found it. It seems the `enable_nbextension` method was removed in 5.0, for no reason I can see.

Perhaps it would work better with:

```python
from notebook.nbextensions import enable_nbextension
enable_nbextension('notebook', 'usability/codefolding/main')
```

?

**Comment by jcb91** [comment]
unfortunately, the 4.x and 5.x methods seem incompatible - `enable_nbextension` was changed from a method of the App class to a function, but isn't present in the same way for either, so perhaps:

```python
from notebook import version_info
ext_require_path = 'usability/codefolding/main'
if version_info[0] > 4:  # notebook 5.x
    from notebook.nbextensions import enable_nbextension
    enable_nbextension('notebook', ext_require_path)
else:  # notebook 4.x
    from notebook.nbextensions import EnableNBExtensionApp
    EnableNBExtensionApp().enable_nbextension(ext_require_path)
```

**Comment by jcb91** [comment]
So, I guess the upshot of this is that we ought to update the main README.md to better reflect the current reality?

**Comment by jcb91** [comment]
see also #627. wiki should now be up-to-date (fingers crossed!)
