### ISSUE TITLE
Suggestion: Expanding variables within Latex equation env

### ISSUE THREAD

**Issue by dslemusp** [ipython-contrib/IPython-notebook-extensions#660]
First I think this functionality is pretty cool. Thank you for putting effort in its development. I have been trying to use the plugin within Latex equation environment as it is shown in the following screenshots 

![screen shot 2016-07-07 at 14 55 04](https://cloud.githubusercontent.com/assets/6799189/16653780/e12430e6-4452-11e6-9fbd-73bcf1e54215.png)

which gets rendered to

![screen shot 2016-07-07 at 14 55 59](https://cloud.githubusercontent.com/assets/6799189/16653792/f4524cca-4452-11e6-801c-c340ae6791d7.png)

Is there any workaround I can use to expand the variable within Latex equation environment?.

Thank you

**Comment by juhasch** [comment]
This would be nice to have, I agree. See my comments in issue #514.
