### ISSUE TITLE
Support non-default base_url

### ISSUE THREAD

**Issue by coderforlife** [ipython-contrib/IPython-notebook-extensions#91]
Currently many of the extensions do not work with non-default base_urls (defaults to /). None of the installation instructions are accurate either. The require lines all need to be something like:

require([IPython.notebook.base_url + 'static/custom/blah.js']);

All paths in the extensions themselves need similar updating, replacing any leading / with IPython.notebook.base_url

**Comment by juhasch** [comment]
Should be fixed
